import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import type { ReportSection } from "./pdf-report";

export type DocxSpec = {
  title: string;
  summary?: string;
  sections: ReportSection[];
  generatedBy?: string;
  generatedAt?: string;
};

export async function buildDocxBuffer(spec: DocxSpec): Promise<Buffer> {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const children: Paragraph[] = [
    new Paragraph({
      text: spec.title.trim(),
      heading: HeadingLevel.TITLE,
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by ${spec.generatedBy ?? "AdeHQ AI employee"} · ${generatedAt}`,
          italics: true,
          color: "6B7280",
        }),
      ],
    }),
  ];

  if (spec.summary?.trim()) {
    children.push(
      new Paragraph({ text: "Summary", heading: HeadingLevel.HEADING_1 }),
      new Paragraph({ text: spec.summary.trim() }),
    );
  }

  for (const section of spec.sections) {
    const paragraphs = section.body
      .split(/\n{2,}/)
      .map((paragraph) => paragraph.trim())
      .filter(Boolean)
      .map((paragraph) => new Paragraph({ text: paragraph }));
    children.push(
      new Paragraph({ text: section.heading.trim(), heading: HeadingLevel.HEADING_1 }),
      ...paragraphs,
    );
  }

  const doc = new Document({
    creator: "AdeHQ",
    title: spec.title,
    description: spec.summary,
    sections: [{ properties: {}, children }],
  });

  return Packer.toBuffer(doc);
}
