import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import type { ReportSection } from "./pdf-report";
import { ARTIFACT_BRAND } from "@/lib/artifacts/design-system";

export type DocxSpec = {
  title: string;
  summary?: string;
  sections: ReportSection[];
  generatedBy?: string;
  generatedAt?: string;
};

function bodyParagraphs(text: string): Paragraph[] {
  return text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .flatMap((paragraph) => {
      const lines = paragraph.split("\n").map((l) => l.trim()).filter(Boolean);
      // Bullet-like lines
      if (lines.every((l) => /^[-•*]/.test(l) || /^\d+\./.test(l))) {
        return lines.map(
          (line) =>
            new Paragraph({
              text: line.replace(/^[-•*]\s*/, "").replace(/^\d+\.\s*/, ""),
              bullet: { level: 0 },
              spacing: { after: 120 },
            }),
        );
      }
      return [
        new Paragraph({
          children: [new TextRun({ text: paragraph, size: 21, font: "Calibri", color: ARTIFACT_BRAND.ink })],
          spacing: { after: 160 },
        }),
      ];
    });
}

function summaryCallout(summary: string): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            borders: {
              top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
              bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
              left: { style: BorderStyle.SINGLE, size: 24, color: ARTIFACT_BRAND.accent },
              right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
            },
            shading: { type: "clear", fill: "F0FDFA" },
            width: { size: 100, type: WidthType.PERCENTAGE },
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "Summary",
                    bold: true,
                    color: ARTIFACT_BRAND.accent,
                    size: 20,
                    font: "Calibri",
                  }),
                ],
                spacing: { after: 80 },
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: summary,
                    size: 20,
                    font: "Calibri",
                    color: ARTIFACT_BRAND.ink,
                  }),
                ],
              }),
            ],
          }),
        ],
      }),
    ],
  });
}

export async function buildDocxBuffer(spec: DocxSpec): Promise<Buffer> {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const generatedBy = spec.generatedBy ?? "AdeHQ AI employee";

  const children: Array<Paragraph | Table> = [
    new Paragraph({
      children: [
        new TextRun({
          text: spec.title.trim(),
          bold: true,
          size: 36,
          font: "Calibri",
          color: ARTIFACT_BRAND.ink,
        }),
      ],
      heading: HeadingLevel.TITLE,
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by ${generatedBy} · ${generatedAt}`,
          italics: true,
          color: ARTIFACT_BRAND.muted,
          size: 18,
          font: "Calibri",
        }),
      ],
      spacing: { after: 280 },
    }),
  ];

  if (spec.summary?.trim()) {
    children.push(summaryCallout(spec.summary.trim()));
    children.push(new Paragraph({ text: "", spacing: { after: 200 } }));
  }

  for (const section of spec.sections) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: section.heading.trim(),
            bold: true,
            size: 26,
            font: "Calibri",
            color: ARTIFACT_BRAND.accent,
          }),
        ],
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 120 },
      }),
      ...bodyParagraphs(section.body),
    );
  }

  const doc = new Document({
    creator: "AdeHQ",
    title: spec.title,
    description: spec.summary,
    sections: [
      {
        properties: {
          page: {
            margin: { top: 720, right: 720, bottom: 720, left: 720 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "AdeHQ",
                    color: ARTIFACT_BRAND.accent,
                    bold: true,
                    size: 16,
                    font: "Calibri",
                  }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "AdeHQ generated document · Drive export",
                    color: ARTIFACT_BRAND.muted,
                    size: 14,
                    font: "Calibri",
                  }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}
