export type ReportSection = {
  heading: string;
  body: string;
};

export type PdfReportSpec = {
  title: string;
  summary?: string;
  sections: ReportSection[];
  generatedBy?: string;
  generatedAt?: string;
};

export function buildReportMarkdown(spec: PdfReportSpec): string {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const lines: string[] = [`# ${spec.title.trim()}`];
  lines.push("", `_Generated by ${spec.generatedBy ?? "AdeHQ AI employee"} · ${generatedAt}_`);
  if (spec.summary?.trim()) {
    lines.push("", "## Summary", "", spec.summary.trim());
  }
  for (const section of spec.sections) {
    lines.push("", `## ${section.heading.trim()}`, "", section.body.trim());
  }
  lines.push("", "---", "", "_AdeHQ generated report — open from Drive for exports._");
  return lines.join("\n");
}

/** Minimal PDF bytes — one page of plain text (no external PDF lib). */
export function buildSimplePdfBuffer(spec: PdfReportSpec): Buffer {
  const text = [
    spec.title,
    spec.summary ? `\n${spec.summary}` : "",
    ...spec.sections.flatMap((s) => [`\n${s.heading}`, s.body]),
    `\n\nGenerated by ${spec.generatedBy ?? "AdeHQ"} · ${spec.generatedAt ?? new Date().toISOString()}`,
  ]
    .join("\n")
    .replace(/[^\x20-\x7E\n\r\t]/g, "?")
    .slice(0, 4000);

  const escaped = text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
    `4 0 obj\n<< /Length ${escaped.length + 50} >>\nstream\nBT\n/F1 11 Tf\n50 740 Td\n(${escaped.replace(/\n/g, ") Tj T* (")}) Tj\nET\nendstream\nendobj\n`,
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj;
  }
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
