export type ReportSection = {
  heading: string;
  body: string;
};

export type PdfReportSpec = {
  title: string;
  summary?: string;
  sections: ReportSection[];
  generatedBy?: string;
  generatedAt?: string;
};

export function buildReportMarkdown(spec: PdfReportSpec): string {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const lines: string[] = [`# ${spec.title.trim()}`];
  lines.push("", `_Generated by ${spec.generatedBy ?? "AdeHQ AI employee"} · ${generatedAt}_`);
  if (spec.summary?.trim()) {
    lines.push("", "## Summary", "", spec.summary.trim());
  }
  for (const section of spec.sections) {
    lines.push("", `## ${section.heading.trim()}`, "", section.body.trim());
  }
  lines.push("", "---", "", "_AdeHQ generated report — open from Drive for exports._");
  return lines.join("\n");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildReportHtml(spec: PdfReportSpec): string {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const sections = spec.sections
    .map(
      (section) => `
        <section>
          <h2>${escapeHtml(section.heading.trim())}</h2>
          ${section.body
            .split(/\n{2,}/)
            .map((paragraph) => `<p>${escapeHtml(paragraph.trim())}</p>`)
            .join("")}
        </section>
      `,
    )
    .join("");

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      @page { size: A4; margin: 28mm 22mm; }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        color: #111827;
        line-height: 1.55;
      }
      header { border-bottom: 4px solid #0f766e; padding-bottom: 18px; margin-bottom: 26px; }
      h1 { font-size: 30px; line-height: 1.1; margin: 0 0 10px; }
      h2 { font-size: 17px; margin: 24px 0 8px; color: #0f766e; }
      p { font-size: 11.5px; margin: 0 0 10px; white-space: pre-wrap; }
      .meta { color: #6b7280; font-size: 10px; }
      .summary { background: #f0fdfa; border-left: 4px solid #0f766e; padding: 12px 14px; margin: 18px 0 20px; }
      footer { position: fixed; bottom: 8mm; left: 22mm; right: 22mm; color: #9ca3af; font-size: 9px; }
    </style>
  </head>
  <body>
    <header>
      <h1>${escapeHtml(spec.title.trim())}</h1>
      <div class="meta">Generated by ${escapeHtml(spec.generatedBy ?? "AdeHQ AI employee")} · ${escapeHtml(generatedAt)}</div>
    </header>
    ${
      spec.summary?.trim()
        ? `<section class="summary"><h2>Summary</h2><p>${escapeHtml(spec.summary.trim())}</p></section>`
        : ""
    }
    ${sections}
    <footer>AdeHQ generated report · Drive export</footer>
  </body>
</html>`;
}

export async function buildHtmlPdfBuffer(spec: PdfReportSpec): Promise<Buffer> {
  try {
    const { chromium } = await import("playwright");
    const browser = await chromium.launch({ headless: true });
    try {
      const page = await browser.newPage();
      await page.setContent(buildReportHtml(spec), { waitUntil: "networkidle" });
      const pdf = await page.pdf({
        format: "A4",
        printBackground: true,
        preferCSSPageSize: true,
      });
      return Buffer.from(pdf);
    } finally {
      await browser.close();
    }
  } catch (error) {
    console.warn("[AdeHQ artifacts] Playwright PDF failed; using simple PDF fallback", error);
    return buildSimplePdfBuffer(spec);
  }
}

/** Minimal PDF bytes — one page of plain text (no external PDF lib). */
export function buildSimplePdfBuffer(spec: PdfReportSpec): Buffer {
  const text = [
    spec.title,
    spec.summary ? `\n${spec.summary}` : "",
    ...spec.sections.flatMap((s) => [`\n${s.heading}`, s.body]),
    `\n\nGenerated by ${spec.generatedBy ?? "AdeHQ"} · ${spec.generatedAt ?? new Date().toISOString()}`,
  ]
    .join("\n")
    .replace(/[^\x20-\x7E\n\r\t]/g, "?")
    .slice(0, 4000);

  const escaped = text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
    `4 0 obj\n<< /Length ${escaped.length + 50} >>\nstream\nBT\n/F1 11 Tf\n50 740 Td\n(${escaped.replace(/\n/g, ") Tj T* (")}) Tj\nET\nendstream\nendobj\n`,
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj;
  }
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
