import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export type ReportSection = {
  heading: string;
  body: string;
};

export type PdfReportSpec = {
  title: string;
  summary?: string;
  sections: ReportSection[];
  generatedBy?: string;
  generatedAt?: string;
};

const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const MARGIN_X = 54;
const MARGIN_TOP = 64;
const MARGIN_BOTTOM = 56;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2;

export function buildReportMarkdown(spec: PdfReportSpec): string {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const lines: string[] = [`# ${spec.title.trim()}`];
  lines.push("", `_Generated by ${spec.generatedBy ?? "AdeHQ AI employee"} · ${generatedAt}_`);
  if (spec.summary?.trim()) {
    lines.push("", "## Summary", "", spec.summary.trim());
  }
  for (const section of spec.sections) {
    lines.push("", `## ${section.heading.trim()}`, "", section.body.trim());
  }
  lines.push("", "---", "", "_AdeHQ generated report — open from Drive for exports._");
  return lines.join("\n");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildReportHtml(spec: PdfReportSpec): string {
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const sections = spec.sections
    .map(
      (section) => `
        <section>
          <h2>${escapeHtml(section.heading.trim())}</h2>
          ${section.body
            .split(/\n{2,}/)
            .map((paragraph) => `<p>${escapeHtml(paragraph.trim())}</p>`)
            .join("")}
        </section>
      `,
    )
    .join("");

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      @page { size: A4; margin: 28mm 22mm; }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        color: #111827;
        line-height: 1.55;
      }
      header { border-bottom: 4px solid #0f766e; padding-bottom: 18px; margin-bottom: 26px; }
      h1 { font-size: 30px; line-height: 1.1; margin: 0 0 10px; }
      h2 { font-size: 17px; margin: 24px 0 8px; color: #0f766e; }
      p { font-size: 11.5px; margin: 0 0 10px; white-space: pre-wrap; }
      .meta { color: #6b7280; font-size: 10px; }
      .summary { background: #f0fdfa; border-left: 4px solid #0f766e; padding: 12px 14px; margin: 18px 0 20px; }
      footer { position: fixed; bottom: 8mm; left: 22mm; right: 22mm; color: #9ca3af; font-size: 9px; }
    </style>
  </head>
  <body>
    <header>
      <h1>${escapeHtml(spec.title.trim())}</h1>
      <div class="meta">Generated by ${escapeHtml(spec.generatedBy ?? "AdeHQ AI employee")} · ${escapeHtml(generatedAt)}</div>
    </header>
    ${
      spec.summary?.trim()
        ? `<section class="summary"><h2>Summary</h2><p>${escapeHtml(spec.summary.trim())}</p></section>`
        : ""
    }
    ${sections}
    <footer>AdeHQ generated report · Drive export</footer>
  </body>
</html>`;
}

/** Helvetica/WinAnsi-safe text for pdf-lib StandardFonts. */
function sanitizePdfText(value: string): string {
  return value
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2022/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?");
}

function wrapLine(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const clean = sanitizePdfText(text);
  if (!clean.trim()) return [""];
  const words = clean.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= maxWidth) {
      current = next;
      continue;
    }
    if (current) lines.push(current);
    if (font.widthOfTextAtSize(word, size) <= maxWidth) {
      current = word;
      continue;
    }
    // Hard-split overlong tokens.
    let chunk = "";
    for (const ch of word) {
      const trial = chunk + ch;
      if (font.widthOfTextAtSize(trial, size) <= maxWidth) {
        chunk = trial;
      } else {
        if (chunk) lines.push(chunk);
        chunk = ch;
      }
    }
    current = chunk;
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

type DrawCtx = {
  doc: PDFDocument;
  page: PDFPage;
  y: number;
  font: PDFFont;
  fontBold: PDFFont;
  pageNumber: number;
};

function drawFooter(ctx: DrawCtx) {
  const label = `AdeHQ generated report · ${ctx.pageNumber}`;
  ctx.page.drawText(label, {
    x: MARGIN_X,
    y: 28,
    size: 8,
    font: ctx.font,
    color: rgb(0.62, 0.64, 0.67),
  });
}

function ensureSpace(ctx: DrawCtx, needed: number) {
  if (ctx.y - needed >= MARGIN_BOTTOM) return;
  drawFooter(ctx);
  ctx.page = ctx.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  ctx.pageNumber += 1;
  ctx.y = PAGE_HEIGHT - MARGIN_TOP;
  // Accent bar on every page
  ctx.page.drawRectangle({
    x: MARGIN_X,
    y: PAGE_HEIGHT - 36,
    width: CONTENT_WIDTH,
    height: 3,
    color: rgb(0.06, 0.46, 0.43),
  });
}

function drawWrapped(
  ctx: DrawCtx,
  text: string,
  opts: { size: number; bold?: boolean; color?: ReturnType<typeof rgb>; lineGap?: number },
) {
  const font = opts.bold ? ctx.fontBold : ctx.font;
  const lineGap = opts.lineGap ?? opts.size * 0.35;
  const lines = wrapLine(text, font, opts.size, CONTENT_WIDTH);
  for (const line of lines) {
    ensureSpace(ctx, opts.size + lineGap);
    ctx.page.drawText(line, {
      x: MARGIN_X,
      y: ctx.y - opts.size,
      size: opts.size,
      font,
      color: opts.color ?? rgb(0.07, 0.09, 0.15),
    });
    ctx.y -= opts.size + lineGap;
  }
}

/**
 * Reliable multi-page PDF for serverless (Vercel) — no Chromium required.
 */
export async function buildPdfLibBuffer(spec: PdfReportSpec): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const generatedAt = spec.generatedAt ?? new Date().toISOString();
  const generatedBy = spec.generatedBy ?? "AdeHQ AI employee";

  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const ctx: DrawCtx = {
    doc,
    page,
    y: PAGE_HEIGHT - MARGIN_TOP,
    font,
    fontBold,
    pageNumber: 1,
  };

  // Header accent
  ctx.page.drawRectangle({
    x: MARGIN_X,
    y: PAGE_HEIGHT - 36,
    width: CONTENT_WIDTH,
    height: 3,
    color: rgb(0.06, 0.46, 0.43),
  });

  drawWrapped(ctx, spec.title.trim() || "Report", {
    size: 22,
    bold: true,
    color: rgb(0.07, 0.09, 0.15),
    lineGap: 6,
  });
  ctx.y -= 4;
  drawWrapped(ctx, `Generated by ${generatedBy} · ${generatedAt}`, {
    size: 9,
    color: rgb(0.42, 0.45, 0.5),
    lineGap: 4,
  });
  ctx.y -= 10;
  ctx.page.drawRectangle({
    x: MARGIN_X,
    y: ctx.y,
    width: CONTENT_WIDTH,
    height: 1,
    color: rgb(0.86, 0.89, 0.91),
  });
  ctx.y -= 18;

  if (spec.summary?.trim()) {
    drawWrapped(ctx, "Summary", {
      size: 13,
      bold: true,
      color: rgb(0.06, 0.46, 0.43),
      lineGap: 4,
    });
    for (const para of spec.summary.trim().split(/\n{2,}/)) {
      drawWrapped(ctx, para.trim(), { size: 10.5, lineGap: 3.5 });
      ctx.y -= 4;
    }
    ctx.y -= 10;
  }

  for (const section of spec.sections) {
    const heading = section.heading.trim() || "Section";
    const body = section.body.trim();
    ctx.y -= 4;
    drawWrapped(ctx, heading, {
      size: 13,
      bold: true,
      color: rgb(0.06, 0.46, 0.43),
      lineGap: 5,
    });
    if (body) {
      for (const para of body.split(/\n{2,}/)) {
        for (const line of para.split("\n")) {
          drawWrapped(ctx, line.trim(), { size: 10.5, lineGap: 3.5 });
        }
        ctx.y -= 6;
      }
    }
    ctx.y -= 6;
  }

  drawFooter(ctx);
  const bytes = await doc.save();
  return Buffer.from(bytes);
}

async function tryPlaywrightPdf(spec: PdfReportSpec): Promise<Buffer | null> {
  if (process.env.ADEHQ_PDF_ENGINE !== "playwright") return null;
  try {
    const { chromium } = await import("playwright");
    const browser = await chromium.launch({ headless: true });
    try {
      const page = await browser.newPage();
      await page.setContent(buildReportHtml(spec), { waitUntil: "networkidle" });
      const pdf = await page.pdf({
        format: "A4",
        printBackground: true,
        preferCSSPageSize: true,
      });
      return Buffer.from(pdf);
    } finally {
      await browser.close();
    }
  } catch (error) {
    console.warn("[AdeHQ artifacts] Playwright PDF failed; using pdf-lib", error);
    return null;
  }
}

/** Prefer pdf-lib on serverless; optional Playwright via ADEHQ_PDF_ENGINE=playwright. */
export async function buildHtmlPdfBuffer(spec: PdfReportSpec): Promise<Buffer> {
  const playwrightPdf = await tryPlaywrightPdf(spec);
  if (playwrightPdf) return playwrightPdf;
  return buildPdfLibBuffer(spec);
}

/** @deprecated Use buildPdfLibBuffer — kept for callers expecting sync bytes. */
export function buildSimplePdfBuffer(spec: PdfReportSpec): Buffer {
  // Sync path cannot use pdf-lib; emit a tiny valid one-page stub and warn.
  // Production paths should always call buildHtmlPdfBuffer / buildPdfLibBuffer.
  console.warn("[AdeHQ artifacts] buildSimplePdfBuffer is deprecated; use buildPdfLibBuffer");
  const title = sanitizePdfText(spec.title || "Report").slice(0, 80);
  const line = title.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  const stream = `BT\n/F1 12 Tf\n50 740 Td\n(${line}) Tj\nET\n`;
  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
    `4 0 obj\n<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}endstream\nendobj\n`,
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj;
  }
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
