import pptxgen from "pptxgenjs";

export type PresentationSlideSpec = {
  title: string;
  bullets?: string[];
  notes?: string;
};

export type PresentationSpec = {
  title: string;
  subtitle?: string;
  slides: PresentationSlideSpec[];
  generatedBy?: string;
  generatedAt?: string;
};

const BRAND = {
  ink: "111827",
  muted: "6B7280",
  accent: "0F766E",
  pale: "CCFBF1",
};

export async function buildPresentationBuffer(spec: PresentationSpec): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "AdeHQ";
  pptx.subject = spec.subtitle ?? spec.title;
  pptx.title = spec.title;
  pptx.company = "AdeHQ";
  pptx.theme = {
    headFontFace: "Aptos Display",
    bodyFontFace: "Aptos",
  };

  const cover = pptx.addSlide();
  cover.background = { color: "F8FAFC" };
  cover.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.333, h: 0.22, fill: { color: BRAND.accent }, line: { color: BRAND.accent } });
  cover.addText(spec.title, {
    x: 0.75,
    y: 1.45,
    w: 11.8,
    h: 0.9,
    fontFace: "Aptos Display",
    fontSize: 34,
    bold: true,
    color: BRAND.ink,
    margin: 0,
  });
  if (spec.subtitle) {
    cover.addText(spec.subtitle, {
      x: 0.78,
      y: 2.45,
      w: 10.8,
      h: 0.5,
      fontSize: 16,
      color: BRAND.muted,
      margin: 0,
    });
  }
  cover.addText(`Generated by ${spec.generatedBy ?? "AdeHQ"} · ${spec.generatedAt ?? new Date().toISOString()}`, {
    x: 0.78,
    y: 6.65,
    w: 8.5,
    h: 0.3,
    fontSize: 9,
    color: BRAND.muted,
    margin: 0,
  });

  for (const slideSpec of spec.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: "FFFFFF" };
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.333, h: 0.12, fill: { color: BRAND.accent }, line: { color: BRAND.accent } });
    slide.addText(slideSpec.title, {
      x: 0.65,
      y: 0.45,
      w: 11.8,
      h: 0.55,
      fontFace: "Aptos Display",
      fontSize: 25,
      bold: true,
      color: BRAND.ink,
      margin: 0,
    });
    const bullets = (slideSpec.bullets ?? []).filter(Boolean);
    if (bullets.length) {
      slide.addText(
        bullets.join("\n"),
        {
          x: 0.85,
          y: 1.35,
          w: 11.4,
          h: 4.7,
          fontSize: 17,
          color: BRAND.ink,
          bullet: { type: "bullet" },
          breakLine: false,
          fit: "shrink",
          paraSpaceAfter: 12,
        },
      );
    }
    if (slideSpec.notes) {
      slide.addNotes(slideSpec.notes);
    }
    slide.addText("AdeHQ", {
      x: 11.7,
      y: 6.95,
      w: 0.9,
      h: 0.2,
      fontSize: 8,
      color: BRAND.muted,
      margin: 0,
    });
  }

  const output = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.isBuffer(output) ? output : Buffer.from(output as ArrayBuffer);
}
