import pptxgen from "pptxgenjs";
import { ARTIFACT_BRAND, ARTIFACT_TYPE } from "@/lib/artifacts/design-system";

export type PresentationSlideSpec = {
  title: string;
  bullets?: string[];
  notes?: string;
  /** Optional layout hint — auto-inferred when omitted. */
  layout?: "bullets" | "two_column" | "kpi" | "section";
};

export type PresentationSpec = {
  title: string;
  subtitle?: string;
  slides: PresentationSlideSpec[];
  generatedBy?: string;
  generatedAt?: string;
};

const BRAND = {
  ink: ARTIFACT_BRAND.ink,
  muted: ARTIFACT_BRAND.muted,
  accent: ARTIFACT_BRAND.accent,
  pale: ARTIFACT_BRAND.pale,
};

function inferLayout(slide: PresentationSlideSpec, index: number): NonNullable<PresentationSlideSpec["layout"]> {
  if (slide.layout) return slide.layout;
  const bullets = slide.bullets ?? [];
  if (/^(agenda|overview|section|part\b)/i.test(slide.title) || bullets.length === 0) {
    return "section";
  }
  if (bullets.length >= 4 && bullets.every((b) => b.length < 48) && index > 0 && index % 3 === 0) {
    return "kpi";
  }
  if (bullets.length >= 4) return "two_column";
  return "bullets";
}

function addFooter(slide: ReturnType<pptxgen["addSlide"]>, page: number, total: number) {
  slide.addText("AdeHQ", {
    x: 11.5,
    y: 6.95,
    w: 1.1,
    h: 0.2,
    fontSize: 8,
    color: BRAND.muted,
    margin: 0,
  });
  slide.addText(`${page} / ${total}`, {
    x: 0.65,
    y: 6.95,
    w: 1.5,
    h: 0.2,
    fontSize: 8,
    color: BRAND.muted,
    margin: 0,
  });
}

export async function buildPresentationBuffer(spec: PresentationSpec): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "AdeHQ";
  pptx.subject = spec.subtitle ?? spec.title;
  pptx.title = spec.title;
  pptx.company = "AdeHQ";
  pptx.theme = {
    headFontFace: ARTIFACT_TYPE.display,
    bodyFontFace: ARTIFACT_TYPE.body,
  };

  const cover = pptx.addSlide();
  cover.background = { color: "F8FAFC" };
  cover.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.333,
    h: 0.22,
    fill: { color: BRAND.accent },
    line: { color: BRAND.accent },
  });
  cover.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 6.8,
    w: 13.333,
    h: 0.7,
    fill: { color: BRAND.pale },
    line: { color: BRAND.pale },
  });
  cover.addText(spec.title, {
    x: 0.75,
    y: 1.45,
    w: 11.8,
    h: 0.9,
    fontFace: ARTIFACT_TYPE.display,
    fontSize: 34,
    bold: true,
    color: BRAND.ink,
    margin: 0,
  });
  if (spec.subtitle) {
    cover.addText(spec.subtitle, {
      x: 0.78,
      y: 2.45,
      w: 10.8,
      h: 0.5,
      fontSize: 16,
      color: BRAND.muted,
      margin: 0,
    });
  }
  cover.addText(
    `Generated by ${spec.generatedBy ?? "AdeHQ"} · ${spec.generatedAt ?? new Date().toISOString()}`,
    {
      x: 0.78,
      y: 6.95,
      w: 8.5,
      h: 0.3,
      fontSize: 9,
      color: BRAND.muted,
      margin: 0,
    },
  );

  const total = spec.slides.length;
  spec.slides.forEach((slideSpec, index) => {
    const layout = inferLayout(slideSpec, index);
    const slide = pptx.addSlide();
    slide.background = { color: "FFFFFF" };
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.12,
      fill: { color: BRAND.accent },
      line: { color: BRAND.accent },
    });

    if (layout === "section") {
      slide.addText(slideSpec.title, {
        x: 0.85,
        y: 2.4,
        w: 11.6,
        h: 1,
        fontFace: ARTIFACT_TYPE.display,
        fontSize: 32,
        bold: true,
        color: BRAND.ink,
        margin: 0,
      });
      const line = (slideSpec.bullets ?? [])[0];
      if (line) {
        slide.addText(line, {
          x: 0.9,
          y: 3.5,
          w: 11,
          h: 0.6,
          fontSize: 16,
          color: BRAND.muted,
          margin: 0,
        });
      }
    } else if (layout === "kpi") {
      slide.addText(slideSpec.title, {
        x: 0.65,
        y: 0.4,
        w: 11.8,
        h: 0.5,
        fontFace: ARTIFACT_TYPE.display,
        fontSize: 24,
        bold: true,
        color: BRAND.ink,
        margin: 0,
      });
      const bullets = (slideSpec.bullets ?? []).slice(0, 4);
      bullets.forEach((b, i) => {
        const x = 0.65 + (i % 2) * 6.2;
        const y = 1.4 + Math.floor(i / 2) * 2.2;
        slide.addShape(pptx.ShapeType.roundRect, {
          x,
          y,
          w: 5.8,
          h: 1.9,
          fill: { color: BRAND.pale },
          line: { color: "CCFBF1" },
          rectRadius: 0.1,
        });
        slide.addText(b, {
          x: x + 0.35,
          y: y + 0.45,
          w: 5.1,
          h: 1,
          fontSize: 16,
          color: BRAND.ink,
          bold: true,
          margin: 0,
        });
      });
    } else if (layout === "two_column") {
      slide.addText(slideSpec.title, {
        x: 0.65,
        y: 0.4,
        w: 11.8,
        h: 0.5,
        fontFace: ARTIFACT_TYPE.display,
        fontSize: 24,
        bold: true,
        color: BRAND.ink,
        margin: 0,
      });
      const bullets = slideSpec.bullets ?? [];
      const mid = Math.ceil(bullets.length / 2);
      const left = bullets.slice(0, mid);
      const right = bullets.slice(mid);
      if (left.length) {
        slide.addText(left.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })), {
          x: 0.75,
          y: 1.25,
          w: 5.6,
          h: 5,
          fontSize: 15,
          color: BRAND.ink,
          paraSpaceAfter: 10,
        });
      }
      if (right.length) {
        slide.addText(right.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })), {
          x: 6.9,
          y: 1.25,
          w: 5.6,
          h: 5,
          fontSize: 15,
          color: BRAND.ink,
          paraSpaceAfter: 10,
        });
      }
    } else {
      slide.addText(slideSpec.title, {
        x: 0.65,
        y: 0.45,
        w: 11.8,
        h: 0.55,
        fontFace: ARTIFACT_TYPE.display,
        fontSize: 25,
        bold: true,
        color: BRAND.ink,
        margin: 0,
      });
      const bullets = (slideSpec.bullets ?? []).filter(Boolean);
      if (bullets.length) {
        slide.addText(
          bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })),
          {
            x: 0.85,
            y: 1.35,
            w: 11.4,
            h: 4.7,
            fontSize: 17,
            color: BRAND.ink,
            paraSpaceAfter: 12,
          },
        );
      }
    }

    if (slideSpec.notes) slide.addNotes(slideSpec.notes);
    addFooter(slide, index + 1, total);
  });

  const output = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.isBuffer(output) ? output : Buffer.from(output as ArrayBuffer);
}
