import ExcelJS from "exceljs";
import type { SpreadsheetSpec } from "./spreadsheet";

export type SpreadsheetBuildMeta = {
  title: string;
  generatedBy?: string;
  generatedAt?: string;
  source?: string;
};

export type EnhancedSpreadsheetSpec = SpreadsheetSpec & {
  meta?: SpreadsheetBuildMeta;
};

function colWidths(columns: string[], rows: SpreadsheetSpec["rows"]): number[] {
  return columns.map((col, colIndex) => {
    const lengths = [col.length, ...rows.map((r) => String(r[colIndex] ?? "").length)];
    return Math.min(48, Math.max(10, ...lengths) + 2);
  });
}

/** Build a polished XLSX with title row, metadata, frozen header, and a metadata sheet. */
export async function buildEnhancedSpreadsheetBuffer(spec: EnhancedSpreadsheetSpec): Promise<Buffer> {
  const sheetName = (spec.sheetName ?? "Data").slice(0, 31);
  const meta = spec.meta;
  const title = meta?.title ?? sheetName;
  const generatedAt = meta?.generatedAt ?? new Date().toISOString();

  const workbook = new ExcelJS.Workbook();
  workbook.creator = "AdeHQ";
  workbook.created = new Date(generatedAt);
  workbook.modified = new Date(generatedAt);

  const sheet = workbook.addWorksheet(sheetName, {
    views: [{ state: "frozen", ySplit: 7 }],
    properties: { defaultRowHeight: 18 },
  });
  sheet.addRow([title]);
  sheet.mergeCells(1, 1, 1, Math.max(1, spec.columns.length));
  const titleCell = sheet.getCell(1, 1);
  titleCell.font = { size: 18, bold: true, color: { argb: "FF111827" } };
  titleCell.alignment = { vertical: "middle" };
  sheet.addRow([]);
  sheet.addRow([`Generated at: ${generatedAt}`]);
  sheet.addRow([`Generated by: ${meta?.generatedBy ?? "AdeHQ AI employee"}`]);
  sheet.addRow([`Source: ${meta?.source ?? "AdeHQ integration tool"}`]);
  sheet.addRow([]);

  const header = sheet.addRow(spec.columns);
  header.font = { bold: true, color: { argb: "FFFFFFFF" } };
  header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF111827" } };
  header.alignment = { vertical: "middle", wrapText: true };

  for (const row of spec.rows) {
    sheet.addRow(row.map((cell) => (cell == null ? "" : cell)));
  }

  const widths = colWidths(spec.columns, spec.rows);
  sheet.columns.forEach((column, index) => {
    column.width = widths[index] ?? 14;
  });
  sheet.autoFilter = {
    from: { row: 7, column: 1 },
    to: { row: 7, column: Math.max(1, spec.columns.length) },
  };
  sheet.eachRow((row, rowNumber) => {
    row.eachCell((cell) => {
      cell.border = {
        top: { style: "thin", color: { argb: rowNumber === 7 ? "FF111827" : "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
      };
      if (rowNumber > 7) {
        cell.alignment = { vertical: "top", wrapText: true };
      }
    });
  });

  const metaSheet = workbook.addWorksheet("Metadata");
  metaSheet.columns = [{ width: 20 }, { width: 52 }];
  metaSheet.addRows([
    ["Property", "Value"],
    ["Title", title],
    ["Generated at", generatedAt],
    ["Generated by", meta?.generatedBy ?? "AdeHQ AI employee"],
    ["Source", meta?.source ?? "AdeHQ integration tool"],
    ["Rows", String(spec.rows.length)],
    ["Columns", String(spec.columns.length)],
  ]);
  metaSheet.getRow(1).font = { bold: true };
  metaSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD9EAFD" } };

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export function sanitizeExportFilename(title: string, ext: string): string {
  const safe = title
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 64);
  return `${safe || "export"}.${ext}`;
}
