import * as XLSX from "xlsx";
import type { SpreadsheetSpec } from "./spreadsheet";

export type SpreadsheetBuildMeta = {
  title: string;
  generatedBy?: string;
  generatedAt?: string;
  source?: string;
};

export type EnhancedSpreadsheetSpec = SpreadsheetSpec & {
  meta?: SpreadsheetBuildMeta;
};

function colWidths(columns: string[], rows: SpreadsheetSpec["rows"]): Array<{ wch: number }> {
  return columns.map((col, colIndex) => {
    const lengths = [col.length, ...rows.map((r) => String(r[colIndex] ?? "").length)];
    return { wch: Math.min(48, Math.max(10, ...lengths) + 2) };
  });
}

/** Build a polished XLSX with title row, metadata, frozen header, and a metadata sheet. */
export function buildEnhancedSpreadsheetBuffer(spec: EnhancedSpreadsheetSpec): Buffer {
  const sheetName = (spec.sheetName ?? "Data").slice(0, 31);
  const meta = spec.meta;
  const title = meta?.title ?? sheetName;
  const generatedAt = meta?.generatedAt ?? new Date().toISOString();

  const headerRowIndex = 4;
  const dataAoA: unknown[][] = [
    [title],
    [],
    [`Generated at: ${generatedAt}`],
    ...(meta?.generatedBy ? [[`Generated by: ${meta.generatedBy}`]] : []),
    ...(meta?.source ? [[`Source: ${meta.source}`]] : []),
    [],
    spec.columns,
    ...spec.rows.map((row) => row.map((c) => (c == null ? "" : c))),
  ];

  const ws = XLSX.utils.aoa_to_sheet(dataAoA);

  if (spec.columns.length > 1) {
    ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: spec.columns.length - 1 } }];
  }

  ws["!freeze"] = {
    xSplit: 0,
    ySplit: headerRowIndex + 1,
    topLeftCell: `A${headerRowIndex + 2}`,
    activePane: "bottomLeft",
    state: "frozen",
  };
  ws["!cols"] = colWidths(spec.columns, spec.rows);

  const metaSheet = XLSX.utils.aoa_to_sheet([
    ["Property", "Value"],
    ["Title", title],
    ["Generated at", generatedAt],
    ["Generated by", meta?.generatedBy ?? "AdeHQ AI employee"],
    ["Source", meta?.source ?? "AdeHQ integration tool"],
    ["Rows", String(spec.rows.length)],
    ["Columns", String(spec.columns.length)],
  ]);
  metaSheet["!cols"] = [{ wch: 18 }, { wch: 42 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.utils.book_append_sheet(wb, metaSheet, "Metadata");
  return Buffer.from(XLSX.write(wb, { type: "buffer", bookType: "xlsx" }));
}

export function sanitizeExportFilename(title: string, ext: string): string {
  const safe = title
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 64);
  return `${safe || "export"}.${ext}`;
}
