// ===========================================================================
// Artifact job handlers — spreadsheet + PDF report generation (Phase 2).
// Registered on module load; polled via GET /api/integrations/jobs/[jobId].
// ===========================================================================

import type { SupabaseClient } from "@supabase/supabase-js";
import { randomUUID } from "node:crypto";
import type { IntegrationJobRecord } from "@/lib/integrations/types";
import { registerJobHandler, type JobHandlerResult } from "./registry";
import { spreadsheetMarkdownPreview } from "@/lib/artifacts/engine/spreadsheet";
import { buildEnhancedSpreadsheetBuffer } from "@/lib/artifacts/engine/spreadsheet-enhanced";
import {
  buildHtmlPdfBuffer,
  buildReportMarkdown,
} from "@/lib/artifacts/engine/pdf-report";
import { buildDocxBuffer } from "@/lib/artifacts/engine/docx";
import { buildPresentationBuffer } from "@/lib/artifacts/engine/presentation";
import { DRIVE_BUCKETS } from "@/lib/drive/constants";
import { exportStoragePath } from "@/lib/drive/storage-sync";
import { recordStorageUsage } from "@/lib/drive/quota-server";
import { uid, nowISO } from "@/lib/utils";
import type {
  ConvertFileArgs,
  CreateDocxArgs,
  CreatePdfReportArgs,
  CreatePresentationArgs,
  CreateSpreadsheetArgs,
  SaveToDriveArgs,
  UpdateSpreadsheetArgs,
} from "@/lib/integrations/registry/tool-definitions";
import { applySpreadsheetTemplate } from "@/lib/artifacts/templates/spreadsheets/index";
import { applyPdfTemplate } from "@/lib/artifacts/templates/pdf/index";

type JobPayload = {
  tool?: string;
  args?: Record<string, unknown>;
  ctx?: {
    roomId?: string;
    topicId?: string;
    employeeId?: string;
    employeeName?: string;
    triggerMessageId?: string;
  };
};

/** Human-readable "Generated by ..." label — falls back to a DB lookup, then the raw id. */
async function resolveGeneratedByLabel(
  client: SupabaseClient,
  workspaceId: string,
  ctx: JobPayload["ctx"],
  employeeId: string,
): Promise<string> {
  if (ctx?.employeeName) return ctx.employeeName;
  const { data } = await client
    .from("ai_employees")
    .select("name")
    .eq("workspace_id", workspaceId)
    .eq("id", employeeId)
    .maybeSingle();
  return data?.name ? String(data.name) : "AdeHQ AI employee";
}

/** Formats an ISO timestamp for display in generated documents, e.g. "July 10, 2026". */
function formatGeneratedAt(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

async function writeArtifactWorkLog(
  client: SupabaseClient,
  job: IntegrationJobRecord,
  params: {
    action: string;
    summary: string;
    artifactId: string;
    toolName: string;
  },
): Promise<void> {
  const ctx = (job.payload as JobPayload).ctx;
  if (!ctx?.roomId || !job.employeeId) return;

  await client.from("work_log_events").insert({
    workspace_id: job.workspaceId,
    id: uid("wl"),
    room_id: ctx.roomId,
    topic_id: ctx.topicId ?? null,
    employee_id: job.employeeId,
    action: params.action,
    summary: params.summary,
    tool_used: params.toolName,
    status: "success",
    related_entity_type: "artifact",
    related_entity_id: params.artifactId,
    created_at: nowISO(),
  });
}

async function persistBinaryExport(
  client: SupabaseClient,
  params: {
    workspaceId: string;
    employeeId: string;
    roomId?: string;
    topicId?: string;
    title: string;
    ext: string;
    mimeType: string;
    buffer: Buffer;
    artifactId: string;
    exportType: string;
  },
): Promise<{ exportId: string; storagePath: string }> {
  const exportId = randomUUID();
  const storagePath = exportStoragePath(
    params.workspaceId,
    exportId,
    params.title,
    params.ext,
  );

  // Storage bucket allowlists are narrower than Office MIME types — upload as
  // octet-stream (same as xlsx/pdf) while keeping the real mime on drive_exports.
  const mimeType =
    params.mimeType === "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" ||
    params.mimeType ===
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
    params.mimeType ===
      "application/vnd.openxmlformats-officedocument.presentationml.presentation" ||
    params.mimeType === "application/pdf"
      ? "application/octet-stream"
      : params.mimeType;

  const { error: uploadError } = await client.storage
    .from(DRIVE_BUCKETS.exports)
    .upload(storagePath, params.buffer, {
      contentType: mimeType,
      upsert: false,
    });
  if (uploadError) throw uploadError;

  const { error: insertError } = await client.from("drive_exports").insert({
    id: exportId,
    workspace_id: params.workspaceId,
    room_id: params.roomId ?? null,
    topic_id: params.topicId ?? null,
    title: params.title,
    export_type: params.exportType,
    storage_bucket: DRIVE_BUCKETS.exports,
    storage_path: storagePath,
    mime_type: params.mimeType,
    size_bytes: params.buffer.byteLength,
    source_artifact_ids: [params.artifactId],
    source_file_ids: [],
    created_by_user_id: null,
    metadata: {
      generatedByEmployeeId: params.employeeId,
      fileExtension: params.ext,
      sourceArtifactId: params.artifactId,
    },
  });
  if (insertError) throw insertError;

  try {
    await recordStorageUsage({
      workspaceId: params.workspaceId,
      eventType: "export",
      bucket: DRIVE_BUCKETS.exports,
      objectPath: storagePath,
      sizeBytes: params.buffer.byteLength,
      deltaBytes: params.buffer.byteLength,
      entityType: "export",
      entityId: exportId,
    });
  } catch (quotaError) {
    console.warn("[AdeHQ drive] recordStorageUsage failed after export", {
      exportId,
      workspaceId: params.workspaceId,
      error: quotaError instanceof Error ? quotaError.message : String(quotaError),
    });
  }

  // Mark the markdown twin so Drive "All files" can hide it in favor of this binary.
  await client
    .from("artifacts")
    .update({
      metadata: {
        integrationGenerated: true,
        binaryCompanion: true,
        binaryExportId: exportId,
        binaryExportExt: params.ext,
        displayTitle: params.title,
      },
    })
    .eq("id", params.artifactId)
    .eq("workspace_id", params.workspaceId);

  return { exportId, storagePath };
}

async function createArtifactRow(
  client: SupabaseClient,
  params: {
    workspaceId: string;
    employeeId: string;
    roomId?: string;
    topicId?: string;
    triggerMessageId?: string;
    title: string;
    artifactType: "report" | "other";
    contentMarkdown: string;
    contentJson: Record<string, unknown>;
  },
): Promise<string> {
  const artifactId = randomUUID();
  const kind =
    typeof params.contentJson.kind === "string" ? String(params.contentJson.kind) : "note";
  // Distinct from the binary export title so Drive doesn't show two identical names.
  const aiSourceTitle = `${params.title} — AI source (${kind}).md`;
  const { error } = await client.from("artifacts").insert({
    workspace_id: params.workspaceId,
    id: artifactId,
    room_id: params.roomId ?? null,
    topic_id: params.topicId ?? null,
    title: aiSourceTitle,
    artifact_type: params.artifactType,
    status: "saved",
    content_markdown: params.contentMarkdown,
    content_json: params.contentJson,
    created_by_type: "ai",
    created_by_id: params.employeeId,
    source_file_ids: [],
    source_message_ids: params.triggerMessageId ? [params.triggerMessageId] : [],
    source_chunk_ids: [],
    source_citations: [],
    metadata: {
      integrationGenerated: true,
      binaryCompanion: true,
      sourceKind: kind,
      displayTitle: params.title,
    },
  });
  if (error) throw error;

  await client.from("artifact_versions").insert({
    artifact_id: artifactId,
    version_number: 1,
    content_markdown: params.contentMarkdown,
    content_json: params.contentJson,
    source_citations: [],
    created_by_type: "ai",
    created_by_id: params.employeeId,
  });

  return artifactId;
}

async function recordArtifactRun(
  client: SupabaseClient,
  job: IntegrationJobRecord,
  params: {
    toolName: string;
    artifactId?: string;
    exportId?: string;
    templateId?: string | null;
    inputPayload: Record<string, unknown>;
    outputPayload: Record<string, unknown>;
  },
): Promise<void> {
  const { error } = await client.from("artifact_runs").insert({
    workspace_id: job.workspaceId,
    integration_tool_run_id: job.toolRunId ?? null,
    integration_job_id: job.id,
    artifact_id: params.artifactId ?? null,
    drive_export_id: params.exportId ?? null,
    tool_name: params.toolName,
    template_id: params.templateId ?? null,
    status: "success",
    input_payload: params.inputPayload,
    output_payload: params.outputPayload,
    completed_at: nowISO(),
  });
  if (error) {
    console.warn("[AdeHQ artifacts] artifact_runs insert skipped", error);
  }
}

async function loadArtifact(
  client: SupabaseClient,
  workspaceId: string,
  artifactId: string,
): Promise<{
  id: string;
  title: string;
  contentMarkdown: string;
  contentJson: Record<string, unknown>;
} | null> {
  const { data, error } = await client
    .from("artifacts")
    .select("id, title, content_markdown, content_json")
    .eq("workspace_id", workspaceId)
    .eq("id", artifactId)
    .maybeSingle();
  if (error) throw error;
  if (!data) return null;
  return {
    id: String(data.id),
    title: String(data.title ?? "Artifact"),
    contentMarkdown: String(data.content_markdown ?? ""),
    contentJson: (data.content_json as Record<string, unknown> | null) ?? {},
  };
}

function markdownToSections(markdown: string): Array<{ heading: string; body: string }> {
  const trimmed = markdown.trim();
  if (!trimmed) return [{ heading: "Notes", body: "No source content was available." }];
  const sections: Array<{ heading: string; body: string }> = [];
  const parts = trimmed.split(/\n(?=##\s+)/g);
  for (const part of parts) {
    const headingMatch = part.match(/^##\s+(.+)$/m);
    if (headingMatch?.[1]) {
      sections.push({
        heading: headingMatch[1].trim(),
        body: part.replace(/^##\s+.+$/m, "").trim() || "—",
      });
    }
  }
  return sections.length ? sections : [{ heading: "Content", body: trimmed.replace(/^#\s+.+$/m, "").trim() || trimmed }];
}

function markdownTitle(markdown: string, fallback: string): string {
  return markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() || fallback;
}

function rowsFromContentJson(contentJson: Record<string, unknown>): {
  columns: string[];
  rows: Array<Array<string | number | boolean | null>>;
  sheetName?: string;
} | null {
  const columns = Array.isArray(contentJson.columns)
    ? contentJson.columns.map((column) => String(column)).filter(Boolean)
    : [];
  const rows = Array.isArray(contentJson.rows)
    ? contentJson.rows.map((row) => (Array.isArray(row) ? row : [row])) as Array<Array<string | number | boolean | null>>
    : [];
  if (!columns.length && !rows.length) return null;
  return {
    columns: columns.length ? columns : ["Value"],
    rows,
    sheetName: contentJson.sheetName ? String(contentJson.sheetName) : undefined,
  };
}

async function handleSpreadsheetJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as CreateSpreadsheetArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for spreadsheet job.");
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);

  const title = args.title.trim();
  const templated = applySpreadsheetTemplate(args);

  const buffer = await buildEnhancedSpreadsheetBuffer({
    sheetName: templated.sheetName,
    columns: templated.columns,
    rows: templated.rows,
    meta: {
      title,
      generatedBy,
      source: templated.template
        ? `artifact.createSpreadsheet (${templated.template})`
        : "artifact.createSpreadsheet",
    },
  });
  const previewMd = spreadsheetMarkdownPreview({
    columns: templated.columns,
    rows: templated.rows,
    sheetName: templated.sheetName,
  });

  const artifactId = await createArtifactRow(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    triggerMessageId: ctx.triggerMessageId,
    title,
    artifactType: "report",
    contentMarkdown: `# ${title}\n\n${previewMd}`,
    contentJson: {
      kind: "spreadsheet",
      template: args.template ?? null,
      columns: templated.columns,
      rows: templated.rows,
      rowCount: templated.rows.length,
      sheetName: templated.sheetName ?? "Sheet1",
    },
  });

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext: "xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    buffer,
    artifactId,
    exportType: "artifact_bundle",
  });

  const summary = `Generated spreadsheet "${title}" (${templated.rows.length} rows) — saved to Drive.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_spreadsheet_created",
    summary,
    artifactId,
    toolName: "artifact.createSpreadsheet",
  });

  const result = { artifactId, exportId, title, rowCount: templated.rows.length, template: args.template };
  await recordArtifactRun(client, job, {
    toolName: "artifact.createSpreadsheet",
    artifactId,
    exportId,
    templateId: args.template ?? null,
    inputPayload: args,
    outputPayload: result,
  });

  return {
    result,
    costUsd: 0.002,
    summary,
  };
}

async function handlePdfReportJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as CreatePdfReportArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for PDF report job.");
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);
  const generatedAt = formatGeneratedAt(new Date().toISOString());

  const spec = applyPdfTemplate(args);
  const contentMarkdown = buildReportMarkdown({ ...spec, generatedBy, generatedAt });
  const pdfBuffer = await buildHtmlPdfBuffer({ ...spec, generatedBy, generatedAt });
  const title = args.title.trim();

  const artifactId = await createArtifactRow(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    triggerMessageId: ctx.triggerMessageId,
    title,
    artifactType: "report",
    contentMarkdown,
    contentJson: {
      kind: "pdf_report",
      template: args.template ?? null,
      sectionCount: spec.sections.length,
      summary: spec.summary ?? null,
    },
  });

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext: "pdf",
    mimeType: "application/pdf",
    buffer: pdfBuffer,
    artifactId,
    exportType: "report",
  });

  const summary = `Generated report "${title}" — saved as artifact and PDF export.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_pdf_created",
    summary,
    artifactId,
    toolName: "artifact.createPdfReport",
  });

  const result = { artifactId, exportId, title, sectionCount: args.sections.length };
  await recordArtifactRun(client, job, {
    toolName: "artifact.createPdfReport",
    artifactId,
    exportId,
    templateId: args.template ?? null,
    inputPayload: args,
    outputPayload: result,
  });

  return {
    result,
    costUsd: 0.005,
    summary,
  };
}

async function handleDocxJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as CreateDocxArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for DOCX job.");
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);

  const title = args.title.trim();
  const generatedAt = formatGeneratedAt(new Date().toISOString());
  const buffer = await buildDocxBuffer({
    title,
    summary: args.summary,
    sections: args.sections,
    generatedBy,
    generatedAt,
  });
  const contentMarkdown = buildReportMarkdown({
    title,
    summary: args.summary,
    sections: args.sections,
    generatedBy,
    generatedAt,
  });

  const artifactId = await createArtifactRow(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    triggerMessageId: ctx.triggerMessageId,
    title,
    artifactType: "report",
    contentMarkdown,
    contentJson: {
      kind: "docx",
      template: args.template ?? null,
      sectionCount: args.sections.length,
      summary: args.summary ?? null,
    },
  });

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext: "docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    buffer,
    artifactId,
    exportType: "document",
  });

  const summary = `Generated document "${title}" — saved as a DOCX export in Drive.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_docx_created",
    summary,
    artifactId,
    toolName: "artifact.createDocx",
  });

  const result = { artifactId, exportId, title, sectionCount: args.sections.length };
  await recordArtifactRun(client, job, {
    toolName: "artifact.createDocx",
    artifactId,
    exportId,
    templateId: args.template ?? null,
    inputPayload: args,
    outputPayload: result,
  });

  return { result, costUsd: 0.004, summary };
}

async function handlePresentationJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as CreatePresentationArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for presentation job.");
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);

  const title = args.title.trim();
  const generatedAt = formatGeneratedAt(new Date().toISOString());
  const buffer = await buildPresentationBuffer({
    title,
    subtitle: args.subtitle,
    slides: args.slides,
    generatedBy,
    generatedAt,
  });
  const contentMarkdown = [
    `# ${title}`,
    args.subtitle ? `\n${args.subtitle}` : "",
    ...args.slides.flatMap((slide) => [
      "",
      `## ${slide.title}`,
      ...(slide.bullets ?? []).map((bullet) => `- ${bullet}`),
      slide.notes ? `\nNotes: ${slide.notes}` : "",
    ]),
  ].join("\n");

  const artifactId = await createArtifactRow(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    triggerMessageId: ctx.triggerMessageId,
    title,
    artifactType: "report",
    contentMarkdown,
    contentJson: {
      kind: "presentation",
      template: args.template ?? null,
      slideCount: args.slides.length,
      slides: args.slides,
    },
  });

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext: "pptx",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    buffer,
    artifactId,
    exportType: "presentation",
  });

  const summary = `Generated presentation "${title}" (${args.slides.length} slides) — saved to Drive.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_presentation_created",
    summary,
    artifactId,
    toolName: "artifact.createPresentation",
  });

  const result = { artifactId, exportId, title, slideCount: args.slides.length };
  await recordArtifactRun(client, job, {
    toolName: "artifact.createPresentation",
    artifactId,
    exportId,
    templateId: args.template ?? null,
    inputPayload: args,
    outputPayload: result,
  });

  return { result, costUsd: 0.006, summary };
}

async function handleUpdateSpreadsheetJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as UpdateSpreadsheetArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for spreadsheet update job.");
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);

  let sourceRows: Array<Array<string | number | boolean | null>> = [];
  let sourceColumns: string[] = [];
  let sourceSheetName: string | undefined;
  if (args.sourceArtifactId) {
    const source = await loadArtifact(client, job.workspaceId, args.sourceArtifactId);
    const sourceSheet = source ? rowsFromContentJson(source.contentJson) : null;
    sourceRows = sourceSheet?.rows ?? [];
    sourceColumns = sourceSheet?.columns ?? [];
    sourceSheetName = sourceSheet?.sheetName;
  }

  const columns = args.columns ?? sourceColumns;
  const providedRows = args.rows ?? [];
  const appendRows = args.appendRows ?? [];
  const rows = providedRows.length ? providedRows : [...sourceRows, ...appendRows];
  const title = args.title.trim();
  const templated = applySpreadsheetTemplate({
    title,
    sheetName: args.sheetName ?? sourceSheetName,
    columns: columns.length ? columns : ["Item", "Status", "Notes"],
    rows,
    template: args.template,
  });

  const buffer = await buildEnhancedSpreadsheetBuffer({
    sheetName: templated.sheetName,
    columns: templated.columns,
    rows: templated.rows,
    meta: {
      title,
      generatedBy,
      source: args.sourceArtifactId
        ? `artifact.updateSpreadsheet (${args.sourceArtifactId})`
        : "artifact.updateSpreadsheet",
    },
  });
  const previewMd = spreadsheetMarkdownPreview({
    columns: templated.columns,
    rows: templated.rows,
    sheetName: templated.sheetName,
  });

  const artifactId = await createArtifactRow(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    triggerMessageId: ctx.triggerMessageId,
    title,
    artifactType: "report",
    contentMarkdown: `# ${title}\n\n${previewMd}`,
    contentJson: {
      kind: "spreadsheet",
      sourceArtifactId: args.sourceArtifactId ?? null,
      template: args.template ?? null,
      columns: templated.columns,
      rows: templated.rows,
      rowCount: templated.rows.length,
      sheetName: templated.sheetName ?? "Sheet1",
    },
  });

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext: "xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    buffer,
    artifactId,
    exportType: "artifact_bundle",
  });

  const summary = `Updated spreadsheet "${title}" (${templated.rows.length} rows) — saved to Drive.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_spreadsheet_updated",
    summary,
    artifactId,
    toolName: "artifact.updateSpreadsheet",
  });

  const result = { artifactId, exportId, title, rowCount: templated.rows.length };
  await recordArtifactRun(client, job, {
    toolName: "artifact.updateSpreadsheet",
    artifactId,
    exportId,
    templateId: args.template ?? null,
    inputPayload: args,
    outputPayload: result,
  });

  return { result, costUsd: 0.003, summary };
}

async function handleConvertFileJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as ConvertFileArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for conversion job.");
  if (!args.sourceArtifactId && !args.sections?.length) {
    throw new Error("artifact.convertFile needs sourceArtifactId or sections in this MVP.");
  }

  const source = args.sourceArtifactId
    ? await loadArtifact(client, job.workspaceId, args.sourceArtifactId)
    : null;
  if (args.sourceArtifactId && !source) throw new Error("Source artifact not found.");

  const sourceMarkdown = source?.contentMarkdown ?? "";
  const title = (args.title ?? source?.title ?? "Converted artifact").trim();
  const sections = args.sections?.length
    ? args.sections
    : markdownToSections(sourceMarkdown);
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);
  const generatedAt = formatGeneratedAt(new Date().toISOString());
  let buffer: Buffer;
  let ext: string = args.targetFormat;
  let mimeType = "application/octet-stream";
  let exportType = "artifact_conversion";

  if (args.targetFormat === "pdf") {
    buffer = await buildHtmlPdfBuffer({ title, sections, generatedBy, generatedAt });
    mimeType = "application/pdf";
    exportType = "report";
  } else if (args.targetFormat === "docx") {
    buffer = await buildDocxBuffer({ title, sections, generatedBy, generatedAt });
    mimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    exportType = "document";
  } else if (args.targetFormat === "pptx") {
    buffer = await buildPresentationBuffer({
      title,
      slides: sections.map((section) => ({
        title: section.heading,
        bullets: section.body.split(/\n+/).map((line) => line.replace(/^[-*]\s*/, "").trim()).filter(Boolean).slice(0, 6),
      })),
      generatedBy,
      generatedAt,
    });
    mimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    exportType = "presentation";
  } else if (args.targetFormat === "xlsx") {
    const sourceSheet = source ? rowsFromContentJson(source.contentJson) : null;
    const columns = sourceSheet?.columns ?? ["Section", "Content"];
    const rows = sourceSheet?.rows?.length
      ? sourceSheet.rows
      : sections.map((section) => [section.heading, section.body]);
    buffer = await buildEnhancedSpreadsheetBuffer({
      sheetName: "Converted",
      columns,
      rows,
      meta: { title, generatedBy, source: "artifact.convertFile" },
    });
    mimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    exportType = "artifact_bundle";
  } else {
    ext = "md";
    buffer = Buffer.from(sourceMarkdown || buildReportMarkdown({ title, sections, generatedBy, generatedAt }), "utf8");
    mimeType = "text/markdown";
  }

  const artifactId = await createArtifactRow(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    triggerMessageId: ctx.triggerMessageId,
    title,
    artifactType: "report",
    contentMarkdown: sourceMarkdown || buildReportMarkdown({ title, sections, generatedBy, generatedAt }),
    contentJson: {
      kind: "conversion",
      targetFormat: args.targetFormat,
      sourceArtifactId: args.sourceArtifactId ?? null,
    },
  });

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext,
    mimeType,
    buffer,
    artifactId,
    exportType,
  });

  const summary = `Converted "${title}" to ${args.targetFormat.toUpperCase()} and saved it to Drive.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_file_converted",
    summary,
    artifactId,
    toolName: "artifact.convertFile",
  });

  const result = { artifactId, exportId, title, targetFormat: args.targetFormat };
  await recordArtifactRun(client, job, {
    toolName: "artifact.convertFile",
    artifactId,
    exportId,
    templateId: null,
    inputPayload: args,
    outputPayload: result,
  });

  return { result, costUsd: 0.005, summary };
}

async function handleSaveToDriveJob(
  client: SupabaseClient,
  job: IntegrationJobRecord,
): Promise<JobHandlerResult> {
  const payload = job.payload as JobPayload;
  const args = payload.args as SaveToDriveArgs;
  const ctx = payload.ctx ?? {};
  const employeeId = job.employeeId ?? ctx.employeeId;
  if (!employeeId) throw new Error("Missing employee for Drive export job.");
  const generatedBy = await resolveGeneratedByLabel(client, job.workspaceId, ctx, employeeId);

  const source = await loadArtifact(client, job.workspaceId, args.artifactId);
  if (!source) throw new Error("Artifact not found.");
  const title = (args.title ?? source.title).trim();
  const sections = markdownToSections(source.contentMarkdown);
  const exportFormat = args.exportFormat ?? "markdown";
  const generatedAt = formatGeneratedAt(new Date().toISOString());

  let buffer: Buffer;
  let ext = "md";
  let mimeType = "text/markdown";
  if (exportFormat === "pdf") {
    ext = "pdf";
    mimeType = "application/pdf";
    buffer = await buildHtmlPdfBuffer({ title, sections, generatedBy, generatedAt });
  } else if (exportFormat === "docx") {
    ext = "docx";
    mimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    buffer = await buildDocxBuffer({ title, sections, generatedBy, generatedAt });
  } else {
    buffer = Buffer.from(source.contentMarkdown, "utf8");
  }

  const { exportId } = await persistBinaryExport(client, {
    workspaceId: job.workspaceId,
    employeeId,
    roomId: ctx.roomId,
    topicId: ctx.topicId,
    title,
    ext,
    mimeType,
    buffer,
    artifactId: source.id,
    exportType: "artifact_export",
  });

  const summary = `Saved "${title}" to Drive as ${exportFormat}.`;
  await writeArtifactWorkLog(client, job, {
    action: "artifact_saved_to_drive",
    summary,
    artifactId: source.id,
    toolName: "artifact.saveToDrive",
  });

  const result = { artifactId: source.id, exportId, title, exportFormat };
  await recordArtifactRun(client, job, {
    toolName: "artifact.saveToDrive",
    artifactId: source.id,
    exportId,
    templateId: null,
    inputPayload: args,
    outputPayload: result,
  });

  return { result, costUsd: 0.002, summary };
}

registerJobHandler("artifact_xlsx", handleSpreadsheetJob);
registerJobHandler("artifact_pdf", handlePdfReportJob);
registerJobHandler("artifact_docx", handleDocxJob);
registerJobHandler("artifact_pptx", handlePresentationJob);
registerJobHandler("artifact_xlsx_update", handleUpdateSpreadsheetJob);
registerJobHandler("artifact_convert", handleConvertFileJob);
registerJobHandler("artifact_save_to_drive", handleSaveToDriveJob);
