import type { ModelMode } from "@/lib/ai/model-catalog";
import type { EmployeeRoleKey } from "@/lib/types";
import type { DepartmentGroup, DepartmentGroupId, RoleLibraryEntry } from "./role-library-types";

export type { DepartmentGroup, DepartmentGroupId, RoleLibraryEntry, RoleInferenceResult, InferenceConfidence, CandidateCapacityProfile } from "./role-library-types";

export const DEPARTMENT_GROUPS: DepartmentGroup[] = [
  { id: "engineering_technical", label: "Engineering & Technical", description: "Build, test, deploy, and support software", browseDefault: true },
  { id: "product_project", label: "Product & Project", description: "Roadmaps, specs, and delivery", browseDefault: true },
  { id: "sales_growth", label: "Sales & Growth", description: "Pipeline, outreach, and revenue", browseDefault: true },
  { id: "marketing_content", label: "Marketing & Content", description: "Campaigns, copy, and brand", browseDefault: true },
  { id: "research_strategy", label: "Research & Strategy", description: "Markets, competitors, and insights", browseDefault: true },
  { id: "operations_admin", label: "Operations & Admin", description: "Coordination, process, and admin", browseDefault: true },
  { id: "finance_analytics", label: "Finance & Analytics", description: "Models, books, and data", browseDefault: true },
  { id: "support_success", label: "Support & Success", description: "Customers, tickets, and retention", browseDefault: true },
  { id: "legal_risk_people", label: "Legal, Risk & People", description: "Compliance, contracts, and HR", browseDefault: true },
  { id: "specialized", label: "Specialized Roles", description: "Niche and industry-specific hires", browseDefault: false },
];

const GROUP_LABELS: Record<DepartmentGroupId, string> = Object.fromEntries(
  DEPARTMENT_GROUPS.map((g) => [g.id, g.label]),
) as Record<DepartmentGroupId, string>;

function personas(
  title: string,
  highTitle: string,
  premiumTitle: string,
  domain: string,
  highFor: string,
  premiumFor: string,
): RoleLibraryEntry["candidatePersonas"] {
  return {
    high_capacity: {
      title: highTitle,
      strengths: ["High-volume output", "Fast first drafts", "Routine task execution", "Quick follow-ups"],
      bestFor: highFor,
    },
    recommended: {
      title,
      strengths: ["Balanced quality and capacity", "Reliable day-to-day work", "Clear communication", "Structured output"],
      bestFor: `Day-to-day ${domain} work for most teams`,
      whyRecommended: `Best balance of quality, weekly AI Work Hours, and cost for typical ${title.toLowerCase()} responsibilities.`,
    },
    premium: {
      title: premiumTitle,
      strengths: ["Deep strategic reasoning", "Complex edge cases", "Senior stakeholder ready", "Higher judgment quality"],
      bestFor: premiumFor,
    },
  };
}

type RoleSeed = Omit<RoleLibraryEntry, "departmentLabel"> & { departmentGroupId: DepartmentGroupId };

function defineRole(seed: RoleSeed): RoleLibraryEntry {
  return {
    ...seed,
    departmentLabel: GROUP_LABELS[seed.departmentGroupId],
  };
}

const ROLE_ENTRIES: RoleLibraryEntry[] = [
  defineRole({
    roleKey: "software_engineer",
    title: "Software Engineer",
    departmentGroupId: "engineering_technical",
    description: "Build features, fix bugs, and ship reliable code",
    popular: true,
    legacyDepartmentId: "engineering",
    employeeRoleKey: "engineering",
    defaultModelMode: "balanced",
    commonUseCases: ["write code", "build features", "ship product", "develop app", "build and ship"],
    searchAliases: ["developer", "coder", "programmer", "swe", "engineer", "full stack"],
    defaultResponsibilities: [
      "Break down product requirements into implementation tasks",
      "Write and review code for new features and bug fixes",
      "Document technical decisions and handoffs",
      "Coordinate with PM and design on feasibility",
    ],
    defaultSuccessMetrics: ["Features shipped on schedule", "Fewer production regressions", "Clear technical documentation", "Faster bug resolution"],
    defaultTechnicalFocus: ["Application development", "Code quality", "System integration"],
    defaultTools: ["GitHub", "Issue tracker", "CI/CD"],
    defaultApprovalRules: ["Ask before production deployments", "Escalate security-sensitive changes"],
    seniorityVariants: { assistant: "Junior Software Engineer", specialist: "Software Engineer", advisor: "Senior Software Architect" },
    candidatePersonas: personas("Software Engineer", "Development Assistant", "Senior Software Architect", "engineering", "High-volume coding tasks and first drafts", "Architecture decisions and complex engineering"),
    questionTemplates: {
      coreWork:
        "Good choice. Should this engineer focus on frontend product work, backend systems, full-stack, AI infrastructure, or QA?",
      coreWorkChips: [
        "Frontend product work",
        "Backend systems",
        "Full-stack",
        "AI infrastructure",
        "QA",
        "Not sure — help me decide",
      ],
    },
  }),
  defineRole({
    roleKey: "qa_test_engineer",
    title: "QA Test Engineer",
    departmentGroupId: "engineering_technical",
    description: "Test apps, find bugs, and improve quality",
    popular: true,
    legacyDepartmentId: "engineering",
    employeeRoleKey: "engineering",
    defaultModelMode: "balanced",
    commonUseCases: ["test my app", "find bugs", "qa", "quality assurance", "manual testing", "automated tests"],
    searchAliases: ["qa", "tester", "quality", "bugs", "testing", "test engineer"],
    defaultResponsibilities: [
      "Create and run test plans for new features",
      "Document bugs with clear reproduction steps",
      "Maintain regression checklists",
      "Validate fixes and edge cases before release",
    ],
    defaultSuccessMetrics: ["Critical bugs caught pre-release", "Clear bug reports", "Regression coverage improved", "Faster test cycles"],
    defaultTechnicalFocus: ["Manual testing", "Test planning", "Bug triage"],
    defaultTools: ["Issue tracker", "Test case docs", "Browser/device matrix"],
    defaultApprovalRules: ["Escalate release-blocking issues immediately"],
    seniorityVariants: { assistant: "QA Assistant", specialist: "QA Test Engineer", advisor: "Senior QA Automation Architect" },
    candidatePersonas: {
      high_capacity: { title: "Test Operations Assistant", strengths: ["Fast bug triage", "Manual QA checklists", "Quick regression runs", "Practical test notes"], bestFor: "High-volume testing and first-pass bug reports" },
      recommended: { title: "QA Test Engineer", strengths: ["Balanced test strategy", "Clear bug reports", "Acceptance criteria", "Structured regression"], bestFor: "Day-to-day QA for most product teams", whyRecommended: "Best balance of test depth and dependable execution for ongoing quality work." },
      premium: { title: "Senior QA Automation Architect", strengths: ["Test architecture", "Edge case analysis", "Automation strategy", "Release risk assessment"], bestFor: "Complex quality strategy and high-risk releases" },
    },
    questionTemplates: {
      coreWork: "What are they mainly testing — web apps, mobile apps, APIs, or internal tools?",
      coreWorkChips: ["Web apps", "Mobile apps", "APIs", "Internal tools", "Not sure — help me decide"],
      focus: "Should they focus on manual testing, automated tests, or bug triage?",
      focusChips: ["Manual testing", "Automated tests", "Bug triage", "All of the above"],
    },
  }),
  defineRole({
    roleKey: "full_stack_developer",
    title: "Full-Stack Developer",
    departmentGroupId: "engineering_technical",
    description: "Work across frontend and backend to ship product",
    legacyDepartmentId: "engineering",
    employeeRoleKey: "engineering",
    defaultModelMode: "balanced",
    commonUseCases: ["full stack", "frontend and backend", "end to end development"],
    searchAliases: ["fullstack", "full-stack", "web developer"],
    defaultResponsibilities: ["Implement features across frontend and backend", "Integrate APIs and UI components", "Debug cross-stack issues", "Ship small features end to end"],
    defaultSuccessMetrics: ["Features shipped end to end", "Fewer integration bugs", "Faster iteration cycles"],
    defaultTechnicalFocus: ["React/Next.js", "APIs", "Database integration"],
    defaultTools: ["GitHub", "Issue tracker", "Local dev environment"],
    defaultApprovalRules: ["Ask before production deployments"],
    seniorityVariants: { specialist: "Full-Stack Developer", advisor: "Senior Full-Stack Engineer" },
    candidatePersonas: personas("Full-Stack Developer", "Full-Stack Development Assistant", "Senior Full-Stack Engineer", "product development", "Routine feature implementation", "Complex full-stack architecture"),
    questionTemplates: { coreWork: "What stack or product area should they work in?", coreWorkChips: ["Web app (React/Next)", "APIs and services", "Internal tools", "New product MVP"] },
  }),
  defineRole({
    roleKey: "devops_engineer",
    title: "DevOps Engineer",
    departmentGroupId: "engineering_technical",
    description: "Deployments, infrastructure, and reliability",
    legacyDepartmentId: "engineering",
    employeeRoleKey: "engineering",
    defaultModelMode: "balanced",
    commonUseCases: ["deploy", "infrastructure", "ci cd", "kubernetes", "aws"],
    searchAliases: ["devops", "sre", "infra", "platform"],
    defaultResponsibilities: ["Maintain CI/CD pipelines", "Monitor production health", "Document runbooks and deployments", "Support release processes"],
    defaultSuccessMetrics: ["Faster safer deployments", "Reduced downtime", "Clear runbooks"],
    defaultTechnicalFocus: ["CI/CD", "Cloud infrastructure", "Observability"],
    defaultTools: ["CI/CD platform", "Cloud console", "Monitoring"],
    defaultApprovalRules: ["Ask before production infra changes", "Escalate security incidents"],
    candidatePersonas: personas("DevOps Engineer", "Release Operations Assistant", "Senior Platform Engineer", "infrastructure", "Routine deploys and monitoring", "Platform architecture and incident response"),
    questionTemplates: { coreWork: "What should they own — deployments, monitoring, cloud infra, or release process?", coreWorkChips: ["Deployments", "Monitoring & alerts", "Cloud infrastructure", "Release coordination"] },
  }),
  defineRole({
    roleKey: "solutions_architect",
    title: "Solutions Architect",
    departmentGroupId: "engineering_technical",
    description: "Design systems, integrations, and technical proposals",
    legacyDepartmentId: "engineering",
    employeeRoleKey: "engineering",
    defaultModelMode: "strong",
    commonUseCases: ["architecture", "integrations", "technical proposals", "enterprise"],
    searchAliases: ["architect", "solutions", "system design"],
    defaultResponsibilities: ["Draft architecture recommendations", "Evaluate integration options", "Support customer implementation planning", "Review technical risk and tradeoffs"],
    defaultSuccessMetrics: ["Clear architecture docs", "Successful integrations", "Fewer rework cycles on technical decisions"],
    defaultTechnicalFocus: ["System design", "Integrations", "Technical proposals"],
    defaultTools: ["Architecture diagrams", "API docs", "Solution templates"],
    defaultApprovalRules: ["Review customer-facing technical commitments"],
    seniorityVariants: { specialist: "Solutions Architect", advisor: "Principal Solutions Architect" },
    candidatePersonas: personas("Solutions Architect", "Technical Proposal Assistant", "Principal Solutions Architect", "architecture", "First-draft proposals and research", "Enterprise architecture and complex integrations"),
    questionTemplates: {
      coreWork: "Should they focus on technical proposals, architecture design, integrations, or customer implementation plans?",
      coreWorkChips: ["Technical proposals", "Architecture design", "Integrations", "Customer implementation plans"],
    },
  }),
  defineRole({
    roleKey: "sales_development_rep",
    title: "Sales Development Rep",
    departmentGroupId: "sales_growth",
    description: "Prospect, qualify leads, and book meetings",
    popular: true,
    legacyDepartmentId: "sales",
    employeeRoleKey: "sales",
    defaultModelMode: "balanced",
    commonUseCases: ["outreach", "leads", "prospecting", "cold email", "sdr", "find customers"],
    searchAliases: ["sdr", "sales dev", "lead gen", "prospecting"],
    defaultResponsibilities: ["Research prospects and accounts", "Draft personalized outreach", "Qualify inbound leads", "Log activity in CRM"],
    defaultSuccessMetrics: ["Qualified meetings booked", "Response rates improved", "Clean CRM hygiene"],
    defaultBusinessFocus: ["Pipeline generation", "Lead qualification"],
    defaultTools: ["CRM", "Email sequences", "Prospecting tools"],
    defaultApprovalRules: ["Ask before sending bulk outreach", "Review custom pricing mentions"],
    seniorityVariants: { specialist: "Sales Development Rep", manager: "SDR Team Lead" },
    candidatePersonas: personas("Sales Development Rep", "Outbound Research Assistant", "Senior SDR Strategist", "sales outreach", "High-volume prospecting and follow-ups", "Strategic account targeting and messaging"),
    questionTemplates: {
      coreWork: "What sales motion should they handle — cold outreach, inbound qualification, follow-ups, or account research?",
      coreWorkChips: ["Cold outreach", "Inbound qualification", "Follow-ups", "Account research"],
    },
  }),
  defineRole({
    roleKey: "lead_generation_specialist",
    title: "Lead Generation Specialist",
    departmentGroupId: "sales_growth",
    description: "Build lists, run campaigns, and fill the pipeline",
    legacyDepartmentId: "sales",
    employeeRoleKey: "sales",
    defaultModelMode: "cheap",
    commonUseCases: ["lead generation", "find leads", "pipeline", "list building"],
    searchAliases: ["lead gen", "leads", "prospects"],
    defaultResponsibilities: ["Build targeted prospect lists", "Run outbound sequences", "Track campaign performance", "Hand off qualified leads to sales"],
    defaultSuccessMetrics: ["Qualified leads per week", "List accuracy", "Campaign conversion rates"],
    defaultBusinessFocus: ["Top-of-funnel pipeline"],
    defaultTools: ["CRM", "Prospecting database", "Email tools"],
    defaultApprovalRules: ["Ask before bulk external outreach"],
    candidatePersonas: personas("Lead Generation Specialist", "Lead List Builder", "Senior Demand Generation Strategist", "lead gen", "High-volume list building", "Campaign strategy and ICP refinement"),
    questionTemplates: { coreWork: "Are they focused on list building, outbound campaigns, or inbound lead capture?", coreWorkChips: ["List building", "Outbound campaigns", "Inbound capture", "All of the above"] },
  }),
  defineRole({
    roleKey: "customer_success_manager",
    title: "Customer Success Manager",
    departmentGroupId: "sales_growth",
    description: "Retain customers, drive adoption, and prevent churn",
    legacyDepartmentId: "sales",
    employeeRoleKey: "sales",
    defaultModelMode: "balanced",
    commonUseCases: ["retain customers", "customer success", "onboarding", "churn"],
    searchAliases: ["csm", "customer success", "retention"],
    defaultResponsibilities: ["Monitor account health and usage", "Run onboarding check-ins", "Identify expansion and risk signals", "Coordinate renewal conversations"],
    defaultSuccessMetrics: ["Higher retention", "Faster time-to-value", "Proactive risk flags"],
    defaultBusinessFocus: ["Customer retention", "Account growth"],
    defaultTools: ["CRM", "Customer health dashboard", "Meeting notes"],
    defaultApprovalRules: ["Escalate at-risk accounts early"],
    candidatePersonas: personas("Customer Success Manager", "Customer Check-in Assistant", "Senior Customer Success Lead", "retention", "High-touch check-ins at scale", "Strategic account planning"),
    questionTemplates: { coreWork: "Should they focus on onboarding, retention, expansion, or health monitoring?", coreWorkChips: ["Onboarding", "Retention", "Expansion", "Health monitoring"] },
  }),
  defineRole({
    roleKey: "market_research_analyst",
    title: "Market Research Analyst",
    departmentGroupId: "research_strategy",
    description: "Research markets, competitors, and trends",
    popular: true,
    legacyDepartmentId: "research",
    employeeRoleKey: "research",
    defaultModelMode: "balanced",
    commonUseCases: ["research market", "competitors", "market size", "industry research"],
    searchAliases: ["market research", "analyst", "competitive", "research"],
    defaultResponsibilities: ["Monitor competitors and market trends", "Produce research briefs", "Synthesize customer and market data", "Support strategic decisions with evidence"],
    defaultSuccessMetrics: ["Timely research briefs", "Actionable insights", "Decision-ready summaries"],
    defaultBusinessFocus: ["Competitive intelligence", "Market sizing"],
    defaultTools: ["Research docs", "Competitive trackers", "Spreadsheets"],
    defaultApprovalRules: ["Cite sources for external-facing research"],
    seniorityVariants: { specialist: "Market Research Analyst", advisor: "Senior Market Strategist" },
    candidatePersonas: personas("Market Research Analyst", "Research Operations Assistant", "Senior Market Strategist", "market research", "Routine scans and summaries", "Strategic market analysis"),
    questionTemplates: {
      coreWork: "What research focus — competitors, market size, customer segments, or pricing?",
      coreWorkChips: ["Competitors", "Market size", "Customer segments", "Pricing"],
    },
  }),
  defineRole({
    roleKey: "business_analyst",
    title: "Business Analyst",
    departmentGroupId: "research_strategy",
    description: "Turn business questions into clear analysis and recommendations",
    popular: true,
    legacyDepartmentId: "product",
    employeeRoleKey: "pm",
    defaultModelMode: "balanced",
    commonUseCases: ["business analysis", "requirements", "process improvement", "stakeholder"],
    searchAliases: ["ba", "business analyst", "analyst"],
    defaultResponsibilities: ["Gather and document business requirements", "Analyze workflows and bottlenecks", "Produce decision-ready summaries", "Support cross-team alignment"],
    defaultSuccessMetrics: ["Clear requirements docs", "Faster decisions", "Fewer scope misunderstandings"],
    defaultBusinessFocus: ["Process clarity", "Requirements quality"],
    defaultTools: ["Docs", "Spreadsheets", "Diagrams"],
    defaultApprovalRules: ["Confirm scope before external commitments"],
    candidatePersonas: personas("Business Analyst", "Analysis Assistant", "Senior Business Analyst", "business analysis", "Routine reporting and summaries", "Complex stakeholder analysis"),
    questionTemplates: { coreWork: "What should they analyze — operations, product, finance, or cross-functional workflows?", coreWorkChips: ["Operations", "Product", "Finance", "Cross-functional workflows"] },
  }),
  defineRole({
    roleKey: "product_manager",
    title: "Product Manager",
    departmentGroupId: "product_project",
    description: "Own roadmap, specs, and product decisions",
    legacyDepartmentId: "product",
    employeeRoleKey: "pm",
    defaultModelMode: "balanced",
    commonUseCases: ["product roadmap", "prd", "product specs", "plan product features"],
    searchAliases: ["pm", "product manager", "roadmap"],
    defaultResponsibilities: ["Write PRDs and product specs", "Prioritize roadmap items", "Synthesize user feedback", "Align engineering and design on scope"],
    defaultSuccessMetrics: ["Clear specs", "Aligned priorities", "Faster discovery-to-delivery"],
    defaultBusinessFocus: ["Product strategy", "User outcomes"],
    defaultTools: ["Notion", "Figma", "Issue tracker"],
    defaultApprovalRules: ["Confirm scope before customer commitments"],
    candidatePersonas: personas("Product Manager", "Product Ops Assistant", "Senior Product Lead", "product management", "Draft specs and backlogs", "Strategic product decisions"),
    questionTemplates: { coreWork: "What should they own — discovery, specs, roadmap, or stakeholder alignment?", coreWorkChips: ["Discovery", "PRDs and specs", "Roadmap", "Stakeholder alignment"] },
  }),
  defineRole({
    roleKey: "project_manager",
    title: "Project Manager",
    departmentGroupId: "product_project",
    description: "Coordinate delivery, timelines, and cross-team work",
    legacyDepartmentId: "operations",
    employeeRoleKey: "operations",
    defaultModelMode: "balanced",
    commonUseCases: ["project management", "timelines", "delivery", "coordination"],
    searchAliases: ["pm", "project manager", "program manager"],
    defaultResponsibilities: ["Track milestones and dependencies", "Run status updates and standups", "Flag risks and blockers", "Keep stakeholders informed"],
    defaultSuccessMetrics: ["On-time delivery", "Clear status reporting", "Fewer surprise blockers"],
    defaultBusinessFocus: ["Delivery visibility", "Cross-team coordination"],
    defaultTools: ["Project tracker", "Docs", "Calendar"],
    defaultApprovalRules: ["Escalate timeline risks early"],
    candidatePersonas: personas("Project Manager", "Project Coordination Assistant", "Senior Delivery Lead", "project delivery", "Status updates and task tracking", "Complex program management"),
    questionTemplates: { coreWork: "What are they managing — product launches, client projects, internal initiatives, or ongoing operations?", coreWorkChips: ["Product launches", "Client projects", "Internal initiatives", "Ongoing operations"] },
  }),
  defineRole({
    roleKey: "marketing_manager",
    title: "Marketing Manager",
    departmentGroupId: "marketing_content",
    description: "Plan campaigns, messaging, and growth initiatives",
    popular: true,
    legacyDepartmentId: "marketing",
    employeeRoleKey: "marketing",
    defaultModelMode: "balanced",
    commonUseCases: ["marketing", "campaigns", "growth", "brand", "find customers"],
    searchAliases: ["marketing", "growth", "campaigns"],
    defaultResponsibilities: ["Plan campaigns and launch calendars", "Draft messaging and positioning", "Coordinate content across channels", "Track campaign performance"],
    defaultSuccessMetrics: ["Campaign velocity", "Consistent messaging", "Pipeline contribution"],
    defaultBusinessFocus: ["Brand awareness", "Demand generation"],
    defaultTools: ["CMS", "Analytics", "Email platform"],
    defaultApprovalRules: ["Ask before publishing paid campaigns"],
    candidatePersonas: personas("Marketing Manager", "Campaign Drafting Assistant", "Senior Growth Strategist", "marketing", "High-volume campaign drafts", "Growth strategy and positioning"),
    questionTemplates: { coreWork: "What should they own — campaigns, brand, content, or growth experiments?", coreWorkChips: ["Campaigns", "Brand messaging", "Content", "Growth experiments"] },
  }),
  defineRole({
    roleKey: "content_strategist",
    title: "Content Strategist",
    departmentGroupId: "marketing_content",
    description: "Plan content themes, calendars, and distribution",
    legacyDepartmentId: "marketing",
    employeeRoleKey: "marketing",
    defaultModelMode: "balanced",
    commonUseCases: ["content strategy", "blog plan", "editorial calendar"],
    searchAliases: ["content", "strategist", "editorial"],
    defaultResponsibilities: ["Build content calendars", "Define themes and pillars", "Align content with funnel stages", "Review content performance"],
    defaultSuccessMetrics: ["Consistent publishing", "Content tied to goals", "Higher engagement"],
    defaultBusinessFocus: ["Content pipeline", "Audience growth"],
    defaultTools: ["CMS", "Content calendar", "Analytics"],
    defaultApprovalRules: ["Review brand-sensitive topics"],
    candidatePersonas: personas("Content Strategist", "Content Planning Assistant", "Senior Content Director", "content strategy", "Calendar and outline drafts", "Editorial strategy"),
    questionTemplates: { coreWork: "What content — blog, social, email, or product marketing?", coreWorkChips: ["Blog", "Social", "Email", "Product marketing"] },
  }),
  defineRole({
    roleKey: "copywriter",
    title: "Copywriter",
    departmentGroupId: "marketing_content",
    description: "Write landing pages, ads, emails, and brand copy",
    legacyDepartmentId: "marketing",
    employeeRoleKey: "marketing",
    defaultModelMode: "balanced",
    commonUseCases: ["write content", "copy", "landing page", "email copy"],
    searchAliases: ["copywriter", "writer", "copy"],
    defaultResponsibilities: ["Draft landing pages and ad copy", "Write email sequences", "Maintain brand voice", "Iterate copy based on feedback"],
    defaultSuccessMetrics: ["Faster copy turnaround", "Consistent voice", "Higher conversion drafts"],
    defaultBusinessFocus: ["Conversion copy", "Brand voice"],
    defaultTools: ["Docs", "CMS", "Brand guidelines"],
    defaultApprovalRules: ["Review public-facing copy before publish"],
    candidatePersonas: personas("Copywriter", "Copy Drafting Assistant", "Senior Brand Copywriter", "copywriting", "High-volume first drafts", "Brand and conversion strategy"),
    questionTemplates: { coreWork: "What copy — website, ads, email, or sales collateral?", coreWorkChips: ["Website", "Ads", "Email", "Sales collateral"] },
  }),
  defineRole({
    roleKey: "social_media_manager",
    title: "Social Media Manager",
    departmentGroupId: "marketing_content",
    description: "Manage social channels, posts, and community",
    legacyDepartmentId: "marketing",
    employeeRoleKey: "marketing",
    defaultModelMode: "cheap",
    commonUseCases: ["social media", "tiktok", "instagram", "linkedin", "influencer"],
    searchAliases: ["social", "instagram", "tiktok", "community"],
    defaultResponsibilities: ["Plan and draft social posts", "Engage with comments and DMs", "Track channel performance", "Maintain brand voice on social"],
    defaultSuccessMetrics: ["Consistent posting", "Engagement growth", "On-brand responses"],
    defaultBusinessFocus: ["Social presence", "Community engagement"],
    defaultTools: ["Scheduling tool", "Analytics", "Asset library"],
    defaultApprovalRules: ["Review sensitive or viral-risk posts"],
    candidatePersonas: personas("Social Media Manager", "Social Posting Assistant", "Senior Social Strategist", "social media", "High-volume posting and replies", "Social strategy and campaigns"),
    questionTemplates: { coreWork: "Which channels — LinkedIn, X, Instagram, TikTok, or multiple?", coreWorkChips: ["LinkedIn", "X / Twitter", "Instagram", "TikTok", "Multiple channels"] },
  }),
  defineRole({
    roleKey: "customer_support_agent",
    title: "Customer Support Agent",
    departmentGroupId: "support_success",
    description: "Reply to tickets and help customers succeed",
    popular: true,
    legacyDepartmentId: "support",
    employeeRoleKey: "support",
    defaultModelMode: "cheap",
    commonUseCases: ["handle support", "tickets", "customer help", "support replies"],
    searchAliases: ["support", "helpdesk", "customer service"],
    defaultResponsibilities: ["Triage and reply to support tickets", "Document common issues", "Escalate complex cases", "Maintain helpful tone and clarity"],
    defaultSuccessMetrics: ["Faster first response", "Higher resolution rate", "Clear escalation notes"],
    defaultBusinessFocus: ["Customer satisfaction", "Response time"],
    defaultTools: ["Helpdesk", "Macros", "Knowledge base"],
    defaultApprovalRules: ["Escalate billing and legal issues"],
    candidatePersonas: personas("Customer Support Agent", "Support Reply Assistant", "Senior Support Specialist", "customer support", "High-volume ticket replies", "Complex escalations and policy"),
    questionTemplates: { coreWork: "What support — email, chat, technical product, or high-touch accounts?", coreWorkChips: ["Email tickets", "Live chat", "Technical product", "High-touch accounts"] },
  }),
  defineRole({
    roleKey: "technical_support_agent",
    title: "Technical Support Agent",
    departmentGroupId: "support_success",
    description: "Troubleshoot technical issues for customers",
    legacyDepartmentId: "support",
    employeeRoleKey: "support",
    defaultModelMode: "balanced",
    commonUseCases: ["technical support", "troubleshoot", "help customers with product"],
    searchAliases: ["tech support", "technical help"],
    defaultResponsibilities: ["Diagnose technical customer issues", "Write reproduction steps for engineering", "Maintain troubleshooting guides", "Escalate bugs with context"],
    defaultSuccessMetrics: ["Faster resolution", "Clear bug reports", "Updated help articles"],
    defaultTechnicalFocus: ["Product troubleshooting", "Bug reproduction"],
    defaultTools: ["Helpdesk", "Internal docs", "Log access"],
    defaultApprovalRules: ["Escalate security issues immediately"],
    candidatePersonas: personas("Technical Support Agent", "Tier-1 Support Assistant", "Senior Technical Support Engineer", "technical support", "Routine troubleshooting", "Complex technical escalations"),
    questionTemplates: { coreWork: "What product type — SaaS, API, mobile app, or developer tools?", coreWorkChips: ["SaaS web app", "API product", "Mobile app", "Developer tools"] },
  }),
  defineRole({
    roleKey: "operations_assistant",
    title: "Operations Assistant",
    departmentGroupId: "operations_admin",
    description: "Coordinate tasks, vendors, and day-to-day ops",
    popular: true,
    legacyDepartmentId: "operations",
    employeeRoleKey: "operations",
    defaultModelMode: "cheap",
    commonUseCases: ["operations", "coordinate", "admin tasks", "improve operations"],
    searchAliases: ["ops", "operations", "coordinator"],
    defaultResponsibilities: ["Track operational tasks and follow-ups", "Coordinate vendors and schedules", "Document processes", "Support cross-team logistics"],
    defaultSuccessMetrics: ["Fewer dropped tasks", "Clear process docs", "Faster coordination cycles"],
    defaultBusinessFocus: ["Operational efficiency"],
    defaultTools: ["Project tracker", "Shared docs", "Calendar"],
    defaultApprovalRules: ["Confirm vendor commitments before sending"],
    candidatePersonas: personas("Operations Assistant", "Ops Task Assistant", "Senior Operations Manager", "operations", "High-volume coordination", "Process design and ops strategy"),
    questionTemplates: { coreWork: "What ops work — vendor coordination, internal logistics, reporting, or process docs?", coreWorkChips: ["Vendor coordination", "Internal logistics", "Reporting", "Process documentation"] },
  }),
  defineRole({
    roleKey: "executive_assistant",
    title: "Executive Assistant",
    departmentGroupId: "operations_admin",
    description: "Calendar, inbox, and executive support",
    legacyDepartmentId: "operations",
    employeeRoleKey: "operations",
    defaultModelMode: "balanced",
    commonUseCases: ["executive assistant", "calendar", "inbox", "admin"],
    searchAliases: ["ea", "assistant", "calendar"],
    defaultResponsibilities: ["Manage calendar and meeting prep", "Draft executive communications", "Track action items", "Coordinate travel and logistics"],
    defaultSuccessMetrics: ["Smoother executive schedule", "Timely follow-ups", "Well-prepared meetings"],
    defaultBusinessFocus: ["Executive leverage"],
    defaultTools: ["Calendar", "Email", "Task tracker"],
    defaultApprovalRules: ["Review external emails before send"],
    candidatePersonas: personas("Executive Assistant", "Admin Support Assistant", "Senior Executive Partner", "executive support", "Scheduling and drafts", "Strategic executive support"),
    questionTemplates: { coreWork: "What support — calendar, inbox, meeting prep, or project tracking?", coreWorkChips: ["Calendar", "Inbox triage", "Meeting prep", "Project tracking"] },
  }),
  defineRole({
    roleKey: "automation_specialist",
    title: "Automation Specialist",
    departmentGroupId: "operations_admin",
    description: "Automate workflows and reduce manual work",
    legacyDepartmentId: "operations",
    employeeRoleKey: "operations",
    defaultModelMode: "balanced",
    commonUseCases: ["automate", "workflow", "zapier", "reduce manual work"],
    searchAliases: ["automation", "workflow", "integrations"],
    defaultResponsibilities: ["Identify repetitive manual workflows", "Design automation recipes", "Document automated processes", "Monitor automation reliability"],
    defaultSuccessMetrics: ["Hours saved per week", "Fewer manual errors", "Documented automations"],
    defaultBusinessFocus: ["Process automation"],
    defaultTools: ["Zapier/Make", "Spreadsheets", "API docs"],
    defaultApprovalRules: ["Review automations touching customer data"],
    candidatePersonas: personas("Automation Specialist", "Workflow Drafting Assistant", "Senior Automation Architect", "automation", "Simple workflow automations", "Cross-system automation design"),
    questionTemplates: { coreWork: "What to automate — data entry, notifications, reporting, or customer workflows?", coreWorkChips: ["Data entry", "Notifications", "Reporting", "Customer workflows"] },
  }),
  defineRole({
    roleKey: "bookkeeping_assistant",
    title: "Bookkeeping Assistant",
    departmentGroupId: "finance_analytics",
    description: "Track expenses, invoices, and books",
    legacyDepartmentId: "finance",
    employeeRoleKey: "operations",
    defaultModelMode: "cheap",
    commonUseCases: ["bookkeeping", "invoices", "expenses", "quickbooks"],
    searchAliases: ["bookkeeper", "accounting", "books"],
    defaultResponsibilities: ["Categorize transactions and expenses", "Track invoices and payments", "Reconcile accounts", "Flag anomalies for review"],
    defaultSuccessMetrics: ["Up-to-date books", "Fewer reconciliation errors", "Timely invoice tracking"],
    defaultBusinessFocus: ["Financial hygiene"],
    defaultTools: ["Accounting software", "Spreadsheets", "Receipt tracker"],
    defaultApprovalRules: ["Never commit payments without approval"],
    candidatePersonas: personas("Bookkeeping Assistant", "Transaction Categorization Assistant", "Senior Bookkeeping Lead", "bookkeeping", "High-volume categorization", "Month-end close support"),
    questionTemplates: { coreWork: "What bookkeeping — expenses, invoicing, reconciliation, or reporting?", coreWorkChips: ["Expenses", "Invoicing", "Reconciliation", "Reporting"] },
  }),
  defineRole({
    roleKey: "financial_analyst",
    title: "Financial Analyst",
    departmentGroupId: "finance_analytics",
    description: "Models, forecasts, and financial reporting",
    legacyDepartmentId: "finance",
    employeeRoleKey: "operations",
    defaultModelMode: "balanced",
    commonUseCases: ["financial model", "forecast", "investor update", "budget"],
    searchAliases: ["finance", "fp&a", "financial analyst"],
    defaultResponsibilities: ["Build and update financial models", "Prepare board and investor summaries", "Track budget vs actuals", "Support scenario planning"],
    defaultSuccessMetrics: ["Accurate forecasts", "Timely reports", "Clear variance analysis"],
    defaultBusinessFocus: ["Financial planning"],
    defaultTools: ["Spreadsheets", "Accounting exports", "Board templates"],
    defaultApprovalRules: ["Review external financial disclosures"],
    candidatePersonas: personas("Financial Analyst", "Financial Reporting Assistant", "Senior FP&A Analyst", "finance", "Routine reports and models", "Strategic financial planning"),
    questionTemplates: { coreWork: "What finance work — modeling, budgeting, investor reporting, or unit economics?", coreWorkChips: ["Modeling", "Budgeting", "Investor reporting", "Unit economics"] },
  }),
  defineRole({
    roleKey: "data_analyst",
    title: "Data Analyst",
    departmentGroupId: "finance_analytics",
    description: "Analyze data, build reports, and find insights",
    legacyDepartmentId: "research",
    employeeRoleKey: "research",
    defaultModelMode: "balanced",
    commonUseCases: ["analyze data", "dashboards", "metrics", "business data"],
    searchAliases: ["data analyst", "analytics", "bi", "sql"],
    defaultResponsibilities: ["Build reports and dashboards", "Analyze trends and anomalies", "Answer ad-hoc data questions", "Document metrics definitions"],
    defaultSuccessMetrics: ["Accurate dashboards", "Faster insights", "Trusted metric definitions"],
    defaultBusinessFocus: ["Data-driven decisions"],
    defaultTools: ["Spreadsheets", "BI tool", "SQL/warehouse"],
    defaultApprovalRules: ["Validate data before external sharing"],
    candidatePersonas: personas("Data Analyst", "Reporting Assistant", "Senior Data Analyst", "data analysis", "Routine reports", "Complex analysis and metric design"),
    questionTemplates: { coreWork: "What data — product usage, sales, marketing, or operations?", coreWorkChips: ["Product usage", "Sales", "Marketing", "Operations"] },
  }),
];

const ROLE_BY_KEY = new Map(ROLE_ENTRIES.map((r) => [r.roleKey, r]));

export function getRoleByKey(roleKey: string | null | undefined): RoleLibraryEntry | undefined {
  if (!roleKey) return undefined;
  return ROLE_BY_KEY.get(roleKey);
}

export function getAllRoles(): RoleLibraryEntry[] {
  return ROLE_ENTRIES;
}

export function getPopularRoles(): RoleLibraryEntry[] {
  return ROLE_ENTRIES.filter((r) => r.popular);
}

export function getRolesByDepartmentGroup(groupId: DepartmentGroupId): RoleLibraryEntry[] {
  return ROLE_ENTRIES.filter((r) => r.departmentGroupId === groupId && !r.specialized);
}

export function getBrowsableDepartmentGroups(): DepartmentGroup[] {
  return DEPARTMENT_GROUPS.filter((g) => g.browseDefault);
}

export function searchRoles(query: string, limit = 8): RoleLibraryEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const scored = ROLE_ENTRIES.map((role) => {
    let score = 0;
    if (role.title.toLowerCase().includes(q)) score += 10;
    if (role.roleKey.includes(q.replace(/\s+/g, "_"))) score += 8;
    for (const alias of role.searchAliases) {
      if (alias.includes(q) || q.includes(alias)) score += 5;
    }
    for (const use of role.commonUseCases) {
      if (use.includes(q) || q.includes(use)) score += 4;
    }
    if (role.description.toLowerCase().includes(q)) score += 2;
    return { role, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((x) => x.role);
}

export function legacyDepartmentIdForRole(roleKey: string | null | undefined): string | null {
  return getRoleByKey(roleKey)?.legacyDepartmentId ?? null;
}

export const LEGACY_DEPT_TO_ROLE: Record<string, string> = {
  product: "product_manager",
  engineering: "software_engineer",
  design: "product_manager",
  research: "market_research_analyst",
  marketing: "marketing_manager",
  sales: "sales_development_rep",
  support: "customer_support_agent",
  operations: "operations_assistant",
  finance: "financial_analyst",
  legal: "business_analyst",
  hr: "operations_assistant",
  pr: "marketing_manager",
  gamedev: "software_engineer",
  custom: "business_analyst",
};

export function migrateLegacyDepartmentId(departmentId: string | null, roleInput?: string): string | null {
  if (!departmentId) return null;
  const fromSearch = roleInput ? searchRoles(roleInput, 1)[0]?.roleKey : null;
  if (fromSearch) return fromSearch;
  return LEGACY_DEPT_TO_ROLE[departmentId] ?? null;
}
