export type PptxSlidePreview = {
  index: number;
  title: string;
  lines: string[];
};

const MAX_SLIDES = 40;
const MAX_LINES_PER_SLIDE = 20;

function decodeXmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

function resolvePptPath(target: string): string {
  const cleaned = target.replace(/^\.\//, "").replace(/^\//, "");
  if (cleaned.startsWith("ppt/")) return cleaned;
  if (cleaned.startsWith("slides/")) return `ppt/${cleaned}`;
  return `ppt/${cleaned}`;
}

function slidePathsFromRels(relsXml: string): string[] {
  const chunks = relsXml.split(/<Relationship\b/i).slice(1);
  const paths: string[] = [];
  for (const chunk of chunks) {
    if (!/Type="[^"]*relationships\/slide"/i.test(chunk)) continue;
    const match = chunk.match(/Target="([^"]+)"/i);
    if (match?.[1]) paths.push(resolvePptPath(match[1]));
  }
  return paths;
}

function slidePathsFromZipKeys(keys: string[]): string[] {
  return keys
    .map((key) => {
      const match = key.match(/^ppt\/slides\/slide(\d+)\.xml$/i);
      return match ? { key, n: Number(match[1]) } : null;
    })
    .filter((row): row is { key: string; n: number } => Boolean(row))
    .sort((a, b) => a.n - b.n)
    .map((row) => row.key);
}

function isFooterNoise(text: string): boolean {
  return (
    /^adehq$/i.test(text) ||
    /^\d+\s*\/\s*\d+$/.test(text) ||
    /^generated by adehq\b/i.test(text)
  );
}

function textsFromSlideXml(xml: string): string[] {
  const raw = [...xml.matchAll(/<a:t(?:\s[^>]*)?>([^<]*)<\/a:t>/g)].map((match) =>
    decodeXmlEntities(match[1] ?? "").replace(/\s+/g, " ").trim(),
  );
  const out: string[] = [];
  for (const text of raw) {
    if (!text || isFooterNoise(text)) continue;
    if (out[out.length - 1] === text) continue;
    out.push(text);
  }
  return out;
}

/** Extract readable slide text from a .pptx (OOXML zip). No Office Online required. */
export async function parsePptxSlides(buffer: ArrayBuffer): Promise<PptxSlidePreview[]> {
  const JSZip = (await import("jszip")).default;
  const zip = await JSZip.loadAsync(buffer);
  const keys = Object.keys(zip.files);

  const relsXml = await zip.file("ppt/_rels/presentation.xml.rels")?.async("string");
  const ordered = (relsXml ? slidePathsFromRels(relsXml) : []).filter((path) =>
    Boolean(zip.file(path)),
  );
  const slidePaths = (ordered.length > 0 ? ordered : slidePathsFromZipKeys(keys)).slice(
    0,
    MAX_SLIDES,
  );

  const slides: PptxSlidePreview[] = [];
  for (let i = 0; i < slidePaths.length; i += 1) {
    const path = slidePaths[i]!;
    const xml = await zip.file(path)?.async("string");
    if (!xml) continue;
    const texts = textsFromSlideXml(xml).slice(0, MAX_LINES_PER_SLIDE);
    if (!texts.length) {
      slides.push({ index: i + 1, title: `Slide ${i + 1}`, lines: [] });
      continue;
    }
    slides.push({
      index: i + 1,
      title: texts[0]!,
      lines: texts.slice(1),
    });
  }
  return slides;
}
