import type { PlaybookDefinitionV1 } from "../contracts";
import { def, step } from "./_helpers";

/** Platform-seeded SaaS product/engineering playbooks. */
export const SAAS_PLAYBOOKS: PlaybookDefinitionV1[] = [
  def({
    key: "product_idea_to_prd",
    name: "Product Idea to PRD",
    description: "Shape a product idea into a structured PRD with acceptance criteria.",
    category: "product",
    industryTags: ["saas"],
    hardWhLimit: 6,
    roleRequirements: [
      { roleKey: "pm", roleTags: ["pm", "product"], capabilityTags: ["reasoning"] },
      { roleKey: "researcher", roleTags: ["researcher"], capabilityTags: ["search"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
      { roleKey: "reviewer", roleTags: ["reviewer", "eng"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "idea", type: "text", required: true, label: "Product idea" },
      { key: "users", type: "text", required: false, label: "Target users" },
    ],
    steps: [
      step({
        stepKey: "problem",
        roleKey: "pm",
        kind: "reasoning",
        objective: "Clarify problem statement and personas",
        capability: "reasoning",
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "research",
        roleKey: "researcher",
        kind: "search",
        objective: "Research comparable solutions and constraints",
        capability: "search",
        dependsOn: ["problem"],
        estimatedWh: 0.7,
      }),
      step({
        stepKey: "requirements",
        roleKey: "pm",
        kind: "reasoning",
        objective: "Define requirements and acceptance criteria",
        capability: "reasoning",
        dependsOn: ["research"],
        estimatedWh: 0.7,
      }),
      step({
        stepKey: "draft_prd",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose PRD document",
        capability: "writing",
        dependsOn: ["requirements"],
        estimatedWh: 0.9,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["problem", "goals", "requirements", "acceptance", "open_questions"],
          outputKey: "prd",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Review PRD for clarity and testability",
        capability: "review",
        dependsOn: ["draft_prd"],
        estimatedWh: 0.4,
        approvalRequired: true,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export PRD",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [{ key: "prd", kind: "document", producedByStepKey: "draft_prd" }],
  }),

  def({
    key: "prd_to_technical_design",
    name: "PRD to Technical Design",
    description: "Translate a PRD into a technical design with risks and milestones.",
    category: "engineering",
    industryTags: ["saas"],
    hardWhLimit: 7,
    roleRequirements: [
      { roleKey: "architect", roleTags: ["architect", "eng"], capabilityTags: ["reasoning", "coding"] },
      { roleKey: "pm", roleTags: ["pm"], capabilityTags: ["reasoning"] },
      { roleKey: "reviewer", roleTags: ["reviewer"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "prd", type: "text", required: true, label: "PRD content or artifact ref" },
    ],
    steps: [
      step({
        stepKey: "ingest",
        roleKey: "pm",
        kind: "reasoning",
        objective: "Extract must-have requirements from PRD",
        capability: "reasoning",
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "architecture",
        roleKey: "architect",
        kind: "reasoning",
        objective: "Propose architecture and data model",
        capability: "reasoning",
        dependsOn: ["ingest"],
        estimatedWh: 1.0,
      }),
      step({
        stepKey: "risks",
        roleKey: "architect",
        kind: "reasoning",
        objective: "Identify risks, alternatives, and milestones",
        capability: "reasoning",
        dependsOn: ["architecture"],
        estimatedWh: 0.5,
      }),
      step({
        stepKey: "draft",
        roleKey: "architect",
        kind: "artifact_compose",
        objective: "Compose technical design doc",
        capability: "writing",
        dependsOn: ["risks"],
        estimatedWh: 0.9,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["overview", "architecture", "apis", "risks", "milestones"],
          outputKey: "tech_design",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Design review for feasibility",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.5,
        approvalRequired: true,
      }),
      step({
        stepKey: "export",
        roleKey: "architect",
        kind: "procedure",
        objective: "Export design doc",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [{ key: "tech_design", kind: "document", producedByStepKey: "draft" }],
  }),

  def({
    key: "sprint_planning",
    name: "Sprint Planning",
    description: "Turn backlog goals into a sprint plan with capacity and risks.",
    category: "engineering",
    industryTags: ["saas"],
    hardWhLimit: 4,
    collaborationMaxLevel: 1,
    roleRequirements: [
      { roleKey: "pm", roleTags: ["pm", "scrum"], capabilityTags: ["reasoning"] },
      { roleKey: "eng_lead", roleTags: ["eng", "lead"], capabilityTags: ["reasoning"] },
    ],
    inputs: [
      { key: "goals", type: "text", required: true, label: "Sprint goals" },
      { key: "backlog", type: "json", required: false, label: "Candidate backlog items" },
      { key: "capacity", type: "json", required: false, label: "Team capacity" },
    ],
    steps: [
      step({
        stepKey: "prioritize",
        roleKey: "pm",
        kind: "reasoning",
        objective: "Prioritize backlog against sprint goals",
        capability: "reasoning",
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "capacity",
        roleKey: "eng_lead",
        kind: "reasoning",
        objective: "Fit work to capacity and dependencies",
        capability: "reasoning",
        dependsOn: ["prioritize"],
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "risks",
        roleKey: "eng_lead",
        kind: "reasoning",
        objective: "Call out risks and stretch items",
        capability: "reasoning",
        dependsOn: ["capacity"],
        estimatedWh: 0.25,
      }),
      step({
        stepKey: "plan_doc",
        roleKey: "pm",
        kind: "artifact_compose",
        objective: "Compose sprint plan document",
        capability: "writing",
        dependsOn: ["risks"],
        estimatedWh: 0.5,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["goals", "committed", "risks", "definition_of_done"],
          outputKey: "sprint_plan",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "eng_lead",
        kind: "review",
        objective: "Confirm plan is achievable",
        capability: "review",
        dependsOn: ["plan_doc"],
        estimatedWh: 0.25,
      }),
    ],
    outputs: [{ key: "sprint_plan", kind: "document", producedByStepKey: "plan_doc" }],
  }),

  def({
    key: "qa_test_plan",
    name: "QA Test Plan",
    description: "Derive a QA test plan and cases from requirements or a PRD.",
    category: "engineering",
    industryTags: ["saas"],
    hardWhLimit: 5,
    roleRequirements: [
      { roleKey: "qa", roleTags: ["qa", "tester"], capabilityTags: ["reasoning"] },
      { roleKey: "pm", roleTags: ["pm"], capabilityTags: ["reasoning"] },
      { roleKey: "reviewer", roleTags: ["reviewer", "eng"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "requirements", type: "text", required: true, label: "Requirements / PRD" },
      { key: "risk_areas", type: "json", required: false, label: "Known risk areas" },
    ],
    steps: [
      step({
        stepKey: "scope",
        roleKey: "qa",
        kind: "reasoning",
        objective: "Define test scope and environments",
        capability: "reasoning",
        estimatedWh: 0.35,
      }),
      step({
        stepKey: "cases",
        roleKey: "qa",
        kind: "reasoning",
        objective: "Draft test cases and priority",
        capability: "reasoning",
        dependsOn: ["scope"],
        estimatedWh: 0.8,
      }),
      step({
        stepKey: "validate_schema",
        roleKey: "qa",
        kind: "procedure",
        objective: "Validate structured test case schema",
        capability: "tool",
        dependsOn: ["cases"],
        procedureKey: "validate_schema",
        estimatedWh: 0.15,
      }),
      step({
        stepKey: "draft",
        roleKey: "qa",
        kind: "artifact_compose",
        objective: "Compose QA test plan document",
        capability: "writing",
        dependsOn: ["validate_schema"],
        estimatedWh: 0.6,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["scope", "cases", "risks", "exit_criteria"],
          outputKey: "test_plan",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Review coverage vs requirements",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.35,
      }),
      step({
        stepKey: "export",
        roleKey: "qa",
        kind: "procedure",
        objective: "Export test plan",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [{ key: "test_plan", kind: "document", producedByStepKey: "draft" }],
  }),

  def({
    key: "release_readiness",
    name: "Release Readiness",
    description: "Assess release readiness across product, eng, and support checklists.",
    category: "engineering",
    industryTags: ["saas"],
    hardWhLimit: 5,
    roleRequirements: [
      { roleKey: "release_manager", roleTags: ["release", "eng"], capabilityTags: ["reasoning"] },
      { roleKey: "qa", roleTags: ["qa"], capabilityTags: ["review"] },
      { roleKey: "pm", roleTags: ["pm"], capabilityTags: ["reasoning"] },
    ],
    inputs: [
      { key: "version", type: "string", required: true, label: "Release version" },
      { key: "changelog", type: "text", required: false, label: "Changelog" },
      { key: "known_issues", type: "json", required: false, label: "Known issues" },
    ],
    steps: [
      step({
        stepKey: "checklist",
        roleKey: "release_manager",
        kind: "reasoning",
        objective: "Assemble release checklist and owners",
        capability: "reasoning",
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "qa_signoff",
        roleKey: "qa",
        kind: "review",
        objective: "QA readiness assessment",
        capability: "review",
        dependsOn: ["checklist"],
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "product_signoff",
        roleKey: "pm",
        kind: "review",
        objective: "Product readiness / comms assessment",
        capability: "review",
        dependsOn: ["checklist"],
        estimatedWh: 0.35,
      }),
      step({
        stepKey: "go_no_go",
        roleKey: "release_manager",
        kind: "reasoning",
        objective: "Produce go/no-go recommendation",
        capability: "reasoning",
        dependsOn: ["qa_signoff", "product_signoff"],
        estimatedWh: 0.35,
      }),
      step({
        stepKey: "draft",
        roleKey: "release_manager",
        kind: "artifact_compose",
        objective: "Compose release readiness report",
        capability: "writing",
        dependsOn: ["go_no_go"],
        estimatedWh: 0.5,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "checklist",
          sectionKeys: ["summary", "checklist", "risks", "decision"],
          outputKey: "readiness_report",
        },
      }),
      step({
        stepKey: "export",
        roleKey: "release_manager",
        kind: "procedure",
        objective: "Export readiness report",
        capability: "export",
        dependsOn: ["draft"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [{ key: "readiness_report", kind: "checklist", producedByStepKey: "draft" }],
  }),

  def({
    key: "bug_triage",
    name: "Bug Triage",
    description: "Triage bug reports into severity, owners, and next actions.",
    category: "engineering",
    industryTags: ["saas"],
    hardWhLimit: 3,
    collaborationMaxLevel: 1,
    roleRequirements: [
      { roleKey: "triager", roleTags: ["qa", "eng", "support"], capabilityTags: ["reasoning"] },
      { roleKey: "eng_lead", roleTags: ["eng", "lead"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "bugs", type: "json", required: true, label: "Bug list / reports" },
      { key: "product_area", type: "string", required: false, label: "Product area" },
    ],
    steps: [
      step({
        stepKey: "normalize",
        roleKey: "triager",
        kind: "procedure",
        objective: "Normalize bug table rows",
        capability: "tool",
        procedureKey: "transform_rows",
        estimatedWh: 0.15,
      }),
      step({
        stepKey: "dedupe",
        roleKey: "triager",
        kind: "procedure",
        objective: "Deduplicate similar reports",
        capability: "tool",
        dependsOn: ["normalize"],
        procedureKey: "deduplicate_rows",
        estimatedWh: 0.15,
      }),
      step({
        stepKey: "classify",
        roleKey: "triager",
        kind: "reasoning",
        objective: "Classify severity and likely owners",
        capability: "reasoning",
        dependsOn: ["dedupe"],
        estimatedWh: 0.5,
      }),
      step({
        stepKey: "draft",
        roleKey: "triager",
        kind: "artifact_compose",
        objective: "Compose triage board summary",
        capability: "writing",
        dependsOn: ["classify"],
        estimatedWh: 0.4,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "checklist",
          sectionKeys: ["summary", "p0", "p1", "p2", "needs_info"],
          outputKey: "triage_summary",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "eng_lead",
        kind: "review",
        objective: "Confirm severity calls and owners",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.25,
      }),
    ],
    outputs: [{ key: "triage_summary", kind: "checklist", producedByStepKey: "draft" }],
  }),
];
