import type { PlaybookDefinitionV1 } from "../contracts";
import { def, step } from "./_helpers";

/** Platform-seeded universal playbooks (role-keyed DAGs). */
export const UNIVERSAL_PLAYBOOKS: PlaybookDefinitionV1[] = [
  def({
    key: "research_to_executive_report",
    name: "Research to Executive Report",
    description: "Research a topic, analyze findings, draft and review an executive report.",
    category: "research",
    hardWhLimit: 8,
    roleRequirements: [
      { roleKey: "researcher", roleTags: ["researcher", "analyst"], capabilityTags: ["search"] },
      { roleKey: "analyst", roleTags: ["analyst"], capabilityTags: ["reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
      { roleKey: "reviewer", roleTags: ["reviewer"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "topic", type: "text", required: true, label: "Research topic" },
      { key: "audience", type: "string", required: false, label: "Audience", defaultValue: "executives" },
    ],
    steps: [
      step({
        stepKey: "scope",
        roleKey: "analyst",
        kind: "reasoning",
        objective: "Clarify research questions and success criteria",
        capability: "reasoning",
        estimatedWh: 0.3,
        inputBindings: [{ target: "topic", source: "run_input", path: "topic" }],
      }),
      step({
        stepKey: "research",
        roleKey: "researcher",
        kind: "search",
        objective: "Gather sources and key facts",
        capability: "search",
        dependsOn: ["scope"],
        estimatedWh: 1.2,
      }),
      step({
        stepKey: "analyze",
        roleKey: "analyst",
        kind: "reasoning",
        objective: "Synthesize insights and recommendations",
        capability: "reasoning",
        dependsOn: ["research"],
        estimatedWh: 0.8,
        inputBindings: [{ target: "findings", source: "step_output", path: "content", stepKey: "research" }],
      }),
      step({
        stepKey: "draft",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose executive report canonical document",
        capability: "writing",
        dependsOn: ["analyze"],
        estimatedWh: 1.0,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["summary", "findings", "recommendations"],
          outputKey: "report",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Review report for accuracy and clarity",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.5,
        approvalRequired: true,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Render DOCX/PDF export",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.3,
      }),
    ],
    outputs: [
      {
        key: "report",
        kind: "document",
        schemaKey: "adehq.document.v1",
        schemaVersion: 1,
        producedByStepKey: "draft",
      },
    ],
    successChecks: [
      { type: "all_steps_completed" },
      { type: "artifact_present", artifactKey: "report", stepKey: "draft" },
    ],
  }),

  def({
    key: "client_brief_to_proposal",
    name: "Client Brief to Proposal",
    description: "Turn a client brief into a structured proposal with pricing narrative.",
    category: "sales",
    hardWhLimit: 7,
    roleRequirements: [
      { roleKey: "strategist", roleTags: ["strategist", "sales"], capabilityTags: ["reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
      { roleKey: "reviewer", roleTags: ["reviewer"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "brief", type: "text", required: true, label: "Client brief" },
      { key: "company", type: "string", required: false, label: "Client company" },
    ],
    steps: [
      step({
        stepKey: "intake",
        roleKey: "strategist",
        kind: "reasoning",
        objective: "Extract requirements, constraints, and success metrics",
        capability: "reasoning",
        estimatedWh: 0.4,
        inputBindings: [{ target: "brief", source: "run_input", path: "brief" }],
      }),
      step({
        stepKey: "research",
        roleKey: "strategist",
        kind: "search",
        objective: "Research client context and competitors",
        capability: "search",
        dependsOn: ["intake"],
        estimatedWh: 0.9,
      }),
      step({
        stepKey: "solution",
        roleKey: "strategist",
        kind: "reasoning",
        objective: "Shape solution approach and scope options",
        capability: "reasoning",
        dependsOn: ["research"],
        estimatedWh: 0.7,
      }),
      step({
        stepKey: "draft_proposal",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose proposal document",
        capability: "writing",
        dependsOn: ["solution"],
        estimatedWh: 1.1,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["overview", "approach", "timeline", "investment"],
          outputKey: "proposal",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Review proposal quality and risk",
        capability: "review",
        dependsOn: ["draft_proposal"],
        estimatedWh: 0.4,
        approvalRequired: true,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export proposal DOCX",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.25,
      }),
    ],
    outputs: [
      { key: "proposal", kind: "document", schemaKey: "adehq.document.v1", producedByStepKey: "draft_proposal" },
    ],
  }),

  def({
    key: "data_file_to_insight_pack",
    name: "Data File to Insight Pack",
    description: "Profile a data file, compute stats, and produce an insight pack with charts.",
    category: "operations",
    hardWhLimit: 6,
    roleRequirements: [
      { roleKey: "analyst", roleTags: ["analyst", "data"], capabilityTags: ["data", "reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
    ],
    inputs: [
      { key: "dataset", type: "file", required: true, label: "Data file" },
      { key: "question", type: "text", required: false, label: "Analysis question" },
    ],
    steps: [
      step({
        stepKey: "normalize",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Normalize CSV/tabular input",
        capability: "tool",
        procedureKey: "normalize_csv",
        estimatedWh: 0.2,
        inputBindings: [{ target: "file", source: "run_input", path: "dataset" }],
      }),
      step({
        stepKey: "profile",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Profile table columns and types",
        capability: "tool",
        dependsOn: ["normalize"],
        procedureKey: "profile_table",
        estimatedWh: 0.25,
      }),
      step({
        stepKey: "stats",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Calculate summary statistics",
        capability: "tool",
        dependsOn: ["profile"],
        procedureKey: "calculate_summary_statistics",
        estimatedWh: 0.3,
      }),
      step({
        stepKey: "charts",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Build chart specs for key metrics",
        capability: "tool",
        dependsOn: ["stats"],
        procedureKey: "bar_chart",
        estimatedWh: 0.25,
      }),
      step({
        stepKey: "insights",
        roleKey: "analyst",
        kind: "reasoning",
        objective: "Interpret stats into business insights",
        capability: "reasoning",
        dependsOn: ["charts"],
        estimatedWh: 0.6,
      }),
      step({
        stepKey: "pack",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose insight pack document + workbook",
        capability: "writing",
        dependsOn: ["insights"],
        estimatedWh: 0.8,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "report",
          sectionKeys: ["summary", "metrics", "charts", "recommendations"],
          outputKey: "insight_pack",
        },
      }),
      step({
        stepKey: "export_xlsx",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Export supporting workbook",
        capability: "export",
        dependsOn: ["pack"],
        procedureKey: "render_xlsx",
        estimatedWh: 0.25,
      }),
    ],
    outputs: [
      { key: "insight_pack", kind: "report", schemaKey: "adehq.document.v1", producedByStepKey: "pack" },
      { key: "workbook", kind: "workbook", schemaKey: "adehq.workbook.v1", producedByStepKey: "export_xlsx" },
    ],
  }),

  def({
    key: "meeting_to_action_pack",
    name: "Meeting to Action Pack",
    description: "Turn meeting notes into decisions, owners, and an action checklist.",
    category: "operations",
    hardWhLimit: 4,
    collaborationMaxLevel: 1,
    roleRequirements: [
      { roleKey: "facilitator", roleTags: ["facilitator", "ops"], capabilityTags: ["reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
    ],
    inputs: [
      { key: "notes", type: "text", required: true, label: "Meeting notes / transcript" },
      { key: "attendees", type: "json", required: false, label: "Attendees" },
    ],
    steps: [
      step({
        stepKey: "extract",
        roleKey: "facilitator",
        kind: "reasoning",
        objective: "Extract decisions, risks, and action items",
        capability: "reasoning",
        estimatedWh: 0.5,
        inputBindings: [{ target: "notes", source: "run_input", path: "notes" }],
      }),
      step({
        stepKey: "owners",
        roleKey: "facilitator",
        kind: "reasoning",
        objective: "Propose owners and due dates",
        capability: "reasoning",
        dependsOn: ["extract"],
        estimatedWh: 0.3,
      }),
      step({
        stepKey: "draft",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose action pack checklist/document",
        capability: "writing",
        dependsOn: ["owners"],
        estimatedWh: 0.5,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "checklist",
          sectionKeys: ["summary", "decisions", "actions"],
          outputKey: "action_pack",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "facilitator",
        kind: "review",
        objective: "Confirm actions are complete and assignable",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.25,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export action pack DOCX",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [
      { key: "action_pack", kind: "checklist", schemaKey: "adehq.document.v1", producedByStepKey: "draft" },
    ],
  }),

  def({
    key: "competitor_analysis",
    name: "Competitor Analysis",
    description: "Research competitors and produce a comparison brief with citations.",
    category: "research",
    hardWhLimit: 7,
    roleRequirements: [
      { roleKey: "researcher", roleTags: ["researcher"], capabilityTags: ["search"] },
      { roleKey: "analyst", roleTags: ["analyst"], capabilityTags: ["reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
    ],
    inputs: [
      { key: "company", type: "string", required: true, label: "Primary company" },
      { key: "competitors", type: "json", required: true, label: "Competitor list" },
    ],
    steps: [
      step({
        stepKey: "landscape",
        roleKey: "researcher",
        kind: "search",
        objective: "Collect competitor landscape sources",
        capability: "search",
        estimatedWh: 1.0,
      }),
      step({
        stepKey: "compare",
        roleKey: "analyst",
        kind: "reasoning",
        objective: "Compare positioning, pricing, strengths/weaknesses",
        capability: "reasoning",
        dependsOn: ["landscape"],
        estimatedWh: 0.9,
      }),
      step({
        stepKey: "citations",
        roleKey: "researcher",
        kind: "procedure",
        objective: "Format citations for claims",
        capability: "tool",
        dependsOn: ["compare"],
        procedureKey: "format_citations",
        estimatedWh: 0.2,
      }),
      step({
        stepKey: "draft",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose competitor analysis brief",
        capability: "writing",
        dependsOn: ["citations"],
        estimatedWh: 0.9,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["overview", "comparison", "implications"],
          outputKey: "brief",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "analyst",
        kind: "review",
        objective: "Review claim coverage and balance",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export brief",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [
      { key: "brief", kind: "document", schemaKey: "adehq.document.v1", producedByStepKey: "draft" },
    ],
  }),

  def({
    key: "campaign_planning",
    name: "Campaign Planning",
    description: "Plan a marketing campaign with messaging, channels, and timeline.",
    category: "marketing",
    hardWhLimit: 6,
    roleRequirements: [
      { roleKey: "marketer", roleTags: ["marketer", "strategist"], capabilityTags: ["reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
      { roleKey: "reviewer", roleTags: ["reviewer"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "goal", type: "text", required: true, label: "Campaign goal" },
      { key: "budget", type: "string", required: false, label: "Budget" },
      { key: "channels", type: "json", required: false, label: "Preferred channels" },
    ],
    steps: [
      step({
        stepKey: "audience",
        roleKey: "marketer",
        kind: "reasoning",
        objective: "Define audience segments and jobs-to-be-done",
        capability: "reasoning",
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "research",
        roleKey: "marketer",
        kind: "search",
        objective: "Research channel norms and messaging angles",
        capability: "search",
        dependsOn: ["audience"],
        estimatedWh: 0.7,
      }),
      step({
        stepKey: "plan",
        roleKey: "marketer",
        kind: "reasoning",
        objective: "Build channel plan, milestones, and KPIs",
        capability: "reasoning",
        dependsOn: ["research"],
        estimatedWh: 0.7,
      }),
      step({
        stepKey: "draft",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose campaign plan document",
        capability: "writing",
        dependsOn: ["plan"],
        estimatedWh: 0.8,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["goal", "audience", "messaging", "channels", "timeline"],
          outputKey: "campaign_plan",
        },
      }),
      step({
        stepKey: "deck",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose campaign presentation outline",
        capability: "writing",
        dependsOn: ["plan"],
        estimatedWh: 0.6,
        artifactIntent: {
          schemaKey: "adehq.presentation.v1",
          schemaVersion: 1,
          kind: "presentation",
          outputKey: "campaign_deck",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Review plan coherence and KPI realism",
        capability: "review",
        dependsOn: ["draft", "deck"],
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "export_deck",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export presentation",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_pptx",
        estimatedWh: 0.25,
      }),
    ],
    outputs: [
      { key: "campaign_plan", kind: "document", producedByStepKey: "draft" },
      { key: "campaign_deck", kind: "presentation", producedByStepKey: "deck" },
    ],
  }),

  def({
    key: "incident_postmortem",
    name: "Incident Postmortem",
    description: "Structured incident timeline, root cause, and remediation plan.",
    category: "operations",
    hardWhLimit: 5,
    collaborationMaxLevel: 2,
    roleRequirements: [
      { roleKey: "incident_lead", roleTags: ["ops", "engineer"], capabilityTags: ["reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
      { roleKey: "reviewer", roleTags: ["reviewer"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "incident_summary", type: "text", required: true, label: "Incident summary" },
      { key: "timeline_notes", type: "text", required: false, label: "Timeline notes" },
    ],
    steps: [
      step({
        stepKey: "timeline",
        roleKey: "incident_lead",
        kind: "reasoning",
        objective: "Build factual incident timeline",
        capability: "reasoning",
        estimatedWh: 0.5,
      }),
      step({
        stepKey: "root_cause",
        roleKey: "incident_lead",
        kind: "reasoning",
        objective: "Identify root cause and contributing factors",
        capability: "reasoning",
        dependsOn: ["timeline"],
        estimatedWh: 0.6,
      }),
      step({
        stepKey: "actions",
        roleKey: "incident_lead",
        kind: "reasoning",
        objective: "Define remediation and prevention actions",
        capability: "reasoning",
        dependsOn: ["root_cause"],
        estimatedWh: 0.4,
      }),
      step({
        stepKey: "draft",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose postmortem document",
        capability: "writing",
        dependsOn: ["actions"],
        estimatedWh: 0.7,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "document",
          sectionKeys: ["summary", "timeline", "root_cause", "actions"],
          outputKey: "postmortem",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Review blameless tone and action completeness",
        capability: "review",
        dependsOn: ["draft"],
        estimatedWh: 0.35,
        approvalRequired: true,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export postmortem",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_docx",
        estimatedWh: 0.2,
      }),
    ],
    outputs: [
      { key: "postmortem", kind: "document", producedByStepKey: "draft" },
    ],
  }),

  def({
    key: "monthly_business_review",
    name: "Monthly Business Review",
    description: "Assemble KPIs, narrative, and an MBR slide deck for leadership.",
    category: "general",
    hardWhLimit: 8,
    roleRequirements: [
      { roleKey: "analyst", roleTags: ["analyst"], capabilityTags: ["data", "reasoning"] },
      { roleKey: "writer", roleTags: ["writer"], capabilityTags: ["writing"] },
      { roleKey: "reviewer", roleTags: ["reviewer", "exec"], capabilityTags: ["review"] },
    ],
    inputs: [
      { key: "period", type: "string", required: true, label: "Review period" },
      { key: "metrics", type: "json", required: false, label: "KPI inputs" },
      { key: "notes", type: "text", required: false, label: "Leadership notes" },
    ],
    steps: [
      step({
        stepKey: "ingest_metrics",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Normalize and profile KPI tables",
        capability: "tool",
        procedureKey: "profile_table",
        estimatedWh: 0.3,
      }),
      step({
        stepKey: "stats",
        roleKey: "analyst",
        kind: "procedure",
        objective: "Calculate period summary statistics",
        capability: "tool",
        dependsOn: ["ingest_metrics"],
        procedureKey: "calculate_summary_statistics",
        estimatedWh: 0.3,
      }),
      step({
        stepKey: "narrative",
        roleKey: "analyst",
        kind: "reasoning",
        objective: "Draft performance narrative and risks",
        capability: "reasoning",
        dependsOn: ["stats"],
        estimatedWh: 0.7,
      }),
      step({
        stepKey: "report",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose MBR written report",
        capability: "writing",
        dependsOn: ["narrative"],
        estimatedWh: 0.8,
        artifactIntent: {
          schemaKey: "adehq.document.v1",
          schemaVersion: 1,
          kind: "report",
          sectionKeys: ["highlights", "metrics", "risks", "asks"],
          outputKey: "mbr_report",
        },
      }),
      step({
        stepKey: "deck",
        roleKey: "writer",
        kind: "artifact_compose",
        objective: "Compose MBR presentation",
        capability: "writing",
        dependsOn: ["narrative"],
        estimatedWh: 0.8,
        artifactIntent: {
          schemaKey: "adehq.presentation.v1",
          schemaVersion: 1,
          kind: "presentation",
          outputKey: "mbr_deck",
        },
      }),
      step({
        stepKey: "review",
        roleKey: "reviewer",
        kind: "review",
        objective: "Executive review of narrative and asks",
        capability: "review",
        dependsOn: ["report", "deck"],
        estimatedWh: 0.5,
        approvalRequired: true,
      }),
      step({
        stepKey: "export",
        roleKey: "writer",
        kind: "procedure",
        objective: "Export deck and report",
        capability: "export",
        dependsOn: ["review"],
        procedureKey: "render_pptx",
        estimatedWh: 0.3,
      }),
    ],
    outputs: [
      { key: "mbr_report", kind: "report", producedByStepKey: "report" },
      { key: "mbr_deck", kind: "presentation", producedByStepKey: "deck" },
    ],
  }),
];
