import type { BusinessArchetype } from "./types";

export const ARCHETYPES: BusinessArchetype[] = [
  {
    id: "software_product",
    name: "Software product company",
    operatingModel: "software",
    description: "Builds and sells its own software product.",
    defaultModuleIds: ["product_management", "engineering", "client_success", "marketing_content"],
    defaultAdaptationId: "adapt_saas",
    matchTerms: ["saas", "software product", "b2b software", "product-led", "subscription software"],
  },
  {
    id: "software_agency",
    name: "Software agency / development house",
    operatingModel: "service",
    description: "Ships client software and digital products.",
    defaultModuleIds: ["product_management", "engineering", "quality_assurance", "customer_support"],
    defaultAdaptationId: "adapt_agency",
    matchTerms: [
      "agency",
      "software house",
      "dev shop",
      "client work",
      "bespoke",
      "development studio",
      "it support",
      "msp",
      "managed service",
    ],
  },
  {
    id: "ecommerce_dtc",
    name: "Ecommerce / DTC brand",
    operatingModel: "commerce",
    description: "Sells products online with orders and fulfilment.",
    defaultModuleIds: ["ecommerce_ops", "customer_support", "performance_marketing", "marketing_content"],
    defaultAdaptationId: "adapt_ecommerce",
    matchTerms: ["shopify", "ecommerce", "e-commerce", "dtc", "online store", "orders"],
  },
  {
    id: "physical_retail",
    name: "Physical retail store",
    operatingModel: "commerce",
    description: "Sells through one or more physical locations.",
    defaultModuleIds: ["inventory_merchandising", "customer_support", "general_operations", "finance_reporting"],
    defaultAdaptationId: "adapt_retail",
    matchTerms: ["retail store", "convenience store", "brick and mortar", "shop floor"],
  },
  {
    id: "restaurant_hospitality",
    name: "Restaurant / café / hospitality",
    operatingModel: "hospitality",
    description: "Food, beverage, or guest hospitality operations.",
    defaultModuleIds: ["scheduling_reservations", "customer_support", "general_operations", "finance_reporting"],
    defaultAdaptationId: "adapt_restaurant",
    matchTerms: ["restaurant", "café", "cafe", "bakery", "hotel", "hospitality", "covers", "menu"],
  },
  {
    id: "professional_services",
    name: "Professional services firm",
    operatingModel: "professional_services",
    description: "Client services such as accounting, legal, or consulting.",
    defaultModuleIds: ["general_operations", "finance_reporting", "sales_pipeline", "executive_ops"],
    defaultAdaptationId: "adapt_professional_services",
    matchTerms: ["accounting", "legal", "consultancy", "consulting", "bookkeeping firm", "advisory"],
  },
  {
    id: "marketing_agency",
    name: "Marketing / creative agency",
    operatingModel: "service",
    description: "Campaigns and creative delivery for clients.",
    defaultModuleIds: ["marketing_content", "sales_pipeline", "client_success", "executive_ops"],
    defaultAdaptationId: "adapt_agency",
    matchTerms: ["marketing agency", "creative agency", "brand studio", "ads agency", "campaigns for"],
  },
  {
    id: "real_estate_property",
    name: "Real estate / property business",
    operatingModel: "service",
    description: "Listings, tenants, property management.",
    defaultModuleIds: ["property_operations", "customer_support", "sales_pipeline", "finance_reporting"],
    defaultAdaptationId: "adapt_property",
    matchTerms: ["real estate", "property management", "leasing", "landlord", "tenants", "apartments", "viewings"],
  },
  {
    id: "education_training",
    name: "Education / tutoring / training",
    operatingModel: "education",
    description: "Teaching, tutoring, or course delivery.",
    defaultModuleIds: ["education_delivery", "customer_support", "marketing_content", "finance_reporting"],
    defaultAdaptationId: "adapt_education",
    matchTerms: ["tutoring", "course", "school", "training", "students", "learners"],
  },
  {
    id: "healthcare_wellness",
    name: "Healthcare / wellness practice",
    operatingModel: "service",
    description: "Clinics, practices, and wellness studios.",
    defaultModuleIds: ["scheduling_reservations", "customer_support", "finance_reporting", "executive_ops"],
    defaultAdaptationId: "adapt_healthcare",
    matchTerms: ["clinic", "dental", "wellness", "therapy", "healthcare", "patients"],
  },
  {
    id: "trades_home_services",
    name: "Trades / home services",
    operatingModel: "service",
    description: "Field jobs, quotes, and scheduling.",
    defaultModuleIds: ["general_operations", "customer_support", "sales_pipeline", "finance_reporting"],
    defaultAdaptationId: "adapt_trades",
    matchTerms: ["plumber", "electrician", "hvac", "home services", "trades", "field service"],
  },
  {
    id: "recruitment_staffing",
    name: "Recruitment / staffing agency",
    operatingModel: "service",
    description: "Hiring pipelines and candidate coordination.",
    defaultModuleIds: ["sales_pipeline", "client_success", "general_operations", "executive_ops"],
    defaultAdaptationId: "adapt_professional_services",
    matchTerms: ["recruitment", "staffing", "talent agency", "hiring agency"],
  },
  {
    id: "logistics_distribution",
    name: "Logistics / distribution",
    operatingModel: "commerce",
    description: "Wholesale, warehousing, and distribution.",
    defaultModuleIds: ["ecommerce_ops", "procurement_suppliers", "customer_support", "finance_reporting"],
    defaultAdaptationId: "adapt_ecommerce",
    matchTerms: ["wholesale", "distribution", "warehouse", "logistics", "fulfilment"],
  },
  {
    id: "nonprofit_community",
    name: "Nonprofit / community organization",
    operatingModel: "nonprofit",
    description: "Programs, donors, and community operations.",
    defaultModuleIds: ["general_operations", "marketing_content", "finance_reporting", "executive_ops"],
    defaultAdaptationId: "adapt_general",
    matchTerms: ["nonprofit", "charity", "community organization", "foundation"],
  },
  {
    id: "creator_media",
    name: "Creator / media business",
    operatingModel: "other",
    description: "Audience, content, and sponsorship operations.",
    defaultModuleIds: ["marketing_content", "performance_marketing", "general_operations", "finance_reporting"],
    defaultAdaptationId: "adapt_creator",
    matchTerms: ["youtube", "creator", "newsletter", "podcast", "media company", "influencer"],
  },
  {
    id: "general_business",
    name: "General business operations",
    operatingModel: "other",
    description: "Flexible back-office coverage for mixed businesses.",
    defaultModuleIds: ["general_operations", "finance_reporting", "executive_ops"],
    defaultAdaptationId: "adapt_general",
    matchTerms: ["general", "small business", "operations"],
  },
];

export function getArchetype(id: string): BusinessArchetype | undefined {
  return ARCHETYPES.find((a) => a.id === id);
}

export function listArchetypes(): BusinessArchetype[] {
  return ARCHETYPES;
}
