import type { CuratedPack } from "./types";
import type { IntakeQuestion } from "../templates/types";

const TEAM_SIZE: IntakeQuestion = {
  id: "team_size_preference",
  prompt: "How big should this team start?",
  type: "single_select",
  options: [
    { value: "lean", label: "Lean" },
    { value: "standard", label: "Standard" },
    { value: "scaled", label: "Scaled" },
  ],
  defaultValue: "lean",
};

const NEEDS_AUTOMATION: IntakeQuestion = {
  id: "needs_automation",
  prompt: "Is there a lot of repetitive manual work to automate?",
  type: "single_select",
  options: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "Not yet" },
  ],
  defaultValue: "no",
};

const PRIMARY_OPS: IntakeQuestion = {
  id: "primary_ops_focus",
  prompt: "What should this team focus on first?",
  type: "single_select",
  options: [
    { value: "vendor_logistics", label: "Vendor & logistics" },
    { value: "financial_hygiene", label: "Financial hygiene" },
    { value: "executive_support", label: "Executive support" },
    { value: "all", label: "A bit of everything" },
  ],
  defaultValue: "all",
};

const NEEDS_SUPPORT: IntakeQuestion = {
  id: "needs_customer_support",
  prompt: "Do you need dedicated customer support coverage?",
  type: "single_select",
  options: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "Not yet" },
  ],
  defaultValue: "yes",
};

const GTM_MOTION: IntakeQuestion = {
  id: "gtm_motion",
  prompt: "What's your primary go-to-market motion?",
  type: "single_select",
  options: [
    { value: "plg", label: "Product-led" },
    { value: "sales_led", label: "Sales-led" },
    { value: "hybrid", label: "Hybrid" },
  ],
  defaultValue: "hybrid",
};

export const CURATED_PACKS: CuratedPack[] = [
  // Commerce
  {
    key: "shopify_store",
    version: "1.0.0",
    name: "Shopify Store",
    description: "Orders, CX, and growth for a Shopify / DTC shop.",
    category: "commerce",
    industry: "ecommerce",
    archetypeId: "ecommerce_dtc",
    moduleIds: ["ecommerce_ops", "customer_support", "performance_marketing", "marketing_content"],
    adaptationId: "adapt_ecommerce",
    intakeQuestions: [TEAM_SIZE, NEEDS_SUPPORT],
    intakeDefaults: { team_size_preference: "lean", needs_customer_support: "yes" },
  },
  {
    key: "ecommerce_brand",
    version: "1.0.0",
    name: "Ecommerce Brand",
    description: "Broader DTC brand ops with content and performance.",
    category: "commerce",
    industry: "ecommerce",
    archetypeId: "ecommerce_dtc",
    moduleIds: ["ecommerce_ops", "customer_support", "performance_marketing", "marketing_content", "finance_reporting"],
    adaptationId: "adapt_ecommerce",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "physical_retail_store",
    version: "1.0.0",
    name: "Physical Retail Store",
    description: "Stock, store CX, and back-office for a retail location.",
    category: "commerce",
    industry: "retail",
    archetypeId: "physical_retail",
    moduleIds: ["inventory_merchandising", "customer_support", "general_operations", "finance_reporting"],
    adaptationId: "adapt_retail",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION, PRIMARY_OPS],
  },
  {
    key: "multi_location_retail",
    version: "1.0.0",
    name: "Multi-location Retail",
    description: "Retail ops with stronger inventory and reporting coverage.",
    category: "commerce",
    industry: "retail",
    archetypeId: "physical_retail",
    moduleIds: ["inventory_merchandising", "customer_support", "general_operations", "finance_reporting", "executive_ops"],
    adaptationId: "adapt_retail",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION, PRIMARY_OPS],
    intakeDefaults: { team_size_preference: "standard" },
  },
  {
    key: "wholesale_distribution",
    version: "1.0.0",
    name: "Wholesale / Distribution",
    description: "Supplier, fulfilment, and B2B order coordination.",
    category: "commerce",
    industry: "logistics",
    archetypeId: "logistics_distribution",
    moduleIds: ["ecommerce_ops", "procurement_suppliers", "customer_support", "finance_reporting"],
    adaptationId: "adapt_ecommerce",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION],
  },
  // Hospitality
  {
    key: "restaurant",
    version: "1.0.0",
    name: "Restaurant",
    description: "Reservations, guest experience, and hospitality ops.",
    category: "hospitality",
    industry: "hospitality",
    archetypeId: "restaurant_hospitality",
    moduleIds: ["scheduling_reservations", "customer_support", "general_operations", "finance_reporting"],
    adaptationId: "adapt_restaurant",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION, PRIMARY_OPS],
    intakeDefaults: { primary_ops_focus: "executive_support", needs_automation: "yes" },
  },
  {
    key: "cafe_bakery",
    version: "1.0.0",
    name: "Café / Bakery",
    description: "Local hospitality with lean guest and ops coverage.",
    category: "hospitality",
    industry: "hospitality",
    archetypeId: "restaurant_hospitality",
    moduleIds: ["scheduling_reservations", "customer_support", "general_operations"],
    adaptationId: "adapt_restaurant",
    intakeQuestions: [TEAM_SIZE, PRIMARY_OPS],
  },
  {
    key: "hotel_guesthouse",
    version: "1.0.0",
    name: "Hotel / Guesthouse",
    description: "Guest communications, scheduling, and property-ish ops.",
    category: "hospitality",
    industry: "hospitality",
    archetypeId: "restaurant_hospitality",
    moduleIds: ["scheduling_reservations", "customer_support", "general_operations", "finance_reporting", "executive_ops"],
    adaptationId: "adapt_restaurant",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "salon_beauty",
    version: "1.0.0",
    name: "Salon / Beauty Business",
    description: "Bookings, guest care, and local ops.",
    category: "hospitality",
    industry: "wellness",
    archetypeId: "healthcare_wellness",
    moduleIds: ["scheduling_reservations", "customer_support", "finance_reporting"],
    adaptationId: "adapt_healthcare",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "gym_fitness",
    version: "1.0.0",
    name: "Gym / Fitness Studio",
    description: "Memberships, scheduling, and member communications.",
    category: "hospitality",
    industry: "wellness",
    archetypeId: "healthcare_wellness",
    moduleIds: ["scheduling_reservations", "customer_support", "marketing_content", "finance_reporting"],
    adaptationId: "adapt_healthcare",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "home_services_trades",
    version: "1.0.0",
    name: "Home Services / Trades",
    description: "Jobs, quotes, customer updates, and field ops.",
    category: "hospitality",
    industry: "trades",
    archetypeId: "trades_home_services",
    moduleIds: ["general_operations", "customer_support", "sales_pipeline", "finance_reporting"],
    adaptationId: "adapt_trades",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION, PRIMARY_OPS],
  },
  // Professional
  {
    key: "accounting_firm",
    version: "1.0.0",
    name: "Accounting Firm",
    description: "Client ops, books, proposals, and partner follow-ups for an accounting practice.",
    category: "professional",
    industry: "professional_services",
    archetypeId: "professional_services",
    // sales_pipeline covers proposal/BD work partners typically drown in;
    // generic customer_support is a weaker fit for a 3-partner firm.
    moduleIds: ["finance_reporting", "general_operations", "executive_ops", "sales_pipeline"],
    adaptationId: "adapt_professional_services",
    intakeQuestions: [TEAM_SIZE, PRIMARY_OPS],
    intakeDefaults: { primary_ops_focus: "financial_hygiene" },
  },
  {
    key: "legal_services",
    version: "1.0.0",
    name: "Legal Services",
    description: "Client intake, matter admin, and careful communications.",
    category: "professional",
    industry: "professional_services",
    archetypeId: "professional_services",
    moduleIds: ["general_operations", "executive_ops", "customer_support", "finance_reporting"],
    adaptationId: "adapt_professional_services",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "consultancy",
    version: "1.0.0",
    name: "Consultancy",
    description: "Pipeline, delivery ops, and client success for a consultancy.",
    category: "professional",
    industry: "professional_services",
    archetypeId: "professional_services",
    moduleIds: ["sales_pipeline", "general_operations", "client_success", "executive_ops"],
    adaptationId: "adapt_professional_services",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "marketing_agency",
    version: "1.0.0",
    name: "Marketing Agency",
    description: "Client campaigns, content, and account care.",
    category: "professional",
    industry: "marketing",
    archetypeId: "marketing_agency",
    moduleIds: ["marketing_content", "sales_pipeline", "client_success", "executive_ops"],
    adaptationId: "adapt_agency",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "recruitment_agency",
    version: "1.0.0",
    name: "Recruitment Agency",
    description: "Candidate/client pipeline and coordination.",
    category: "professional",
    industry: "recruitment",
    archetypeId: "recruitment_staffing",
    moduleIds: ["sales_pipeline", "client_success", "general_operations", "executive_ops"],
    adaptationId: "adapt_professional_services",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "real_estate_agency",
    version: "1.0.0",
    name: "Real Estate Agency",
    description: "Listings, prospect pipeline, and client care.",
    category: "professional",
    industry: "real_estate",
    archetypeId: "real_estate_property",
    moduleIds: ["property_operations", "sales_pipeline", "customer_support", "marketing_content"],
    adaptationId: "adapt_property",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "property_management",
    version: "1.0.0",
    name: "Property Management Company",
    description: "Tenant requests, maintenance, and property ops.",
    category: "professional",
    industry: "real_estate",
    archetypeId: "real_estate_property",
    moduleIds: ["property_operations", "customer_support", "finance_reporting", "general_operations"],
    adaptationId: "adapt_property",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION],
  },
  // Technology — software_house / saas_startup stay as legacy TemplateManifest
  // aliases in templates/registry.ts (composition-test parity). Ontology adds
  // adjacent tech packs here.
  {
    key: "mobile_app_startup",
    version: "1.0.0",
    name: "Mobile App Startup",
    description: "Product + engineering focused mobile team.",
    category: "technology",
    industry: "software",
    archetypeId: "software_product",
    moduleIds: ["product_management", "engineering", "quality_assurance", "marketing_content"],
    adaptationId: "adapt_saas",
    intakeQuestions: [TEAM_SIZE, GTM_MOTION],
  },
  {
    key: "ai_startup",
    version: "1.0.0",
    name: "AI Startup",
    description: "Product, engineering, research, and GTM for an AI product.",
    category: "technology",
    industry: "saas",
    archetypeId: "software_product",
    moduleIds: ["product_management", "engineering", "research_intelligence", "client_success", "marketing_content"],
    adaptationId: "adapt_saas",
    intakeQuestions: [TEAM_SIZE, GTM_MOTION],
  },
  {
    key: "it_support_provider",
    version: "1.0.0",
    name: "IT Support Provider",
    description: "Technical support and client ops for an MSP-style business.",
    category: "technology",
    industry: "it_services",
    archetypeId: "software_agency",
    moduleIds: ["customer_support", "general_operations", "client_success", "sales_pipeline"],
    adaptationId: "adapt_agency",
    intakeQuestions: [TEAM_SIZE, NEEDS_SUPPORT],
    intakeDefaults: { needs_customer_support: "yes" },
  },
  // Education & media
  {
    key: "tutoring_business",
    version: "1.0.0",
    name: "Tutoring Business",
    description: "Sessions, learner support, and scheduling.",
    category: "education_media",
    industry: "education",
    archetypeId: "education_training",
    moduleIds: ["education_delivery", "customer_support", "scheduling_reservations", "finance_reporting"],
    adaptationId: "adapt_education",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "online_course_business",
    version: "1.0.0",
    name: "Online Course Business",
    description: "Course delivery, content, and learner care.",
    category: "education_media",
    industry: "education",
    archetypeId: "education_training",
    moduleIds: ["education_delivery", "marketing_content", "customer_support", "finance_reporting"],
    adaptationId: "adapt_education",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "creator_youtube",
    version: "1.0.0",
    name: "Creator / YouTube Business",
    description: "Content cadence, growth, and studio ops.",
    category: "education_media",
    industry: "media",
    archetypeId: "creator_media",
    moduleIds: ["marketing_content", "performance_marketing", "general_operations"],
    adaptationId: "adapt_creator",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "newsletter_media",
    version: "1.0.0",
    name: "Newsletter / Media Company",
    description: "Editorial cadence, audience growth, and ops.",
    category: "education_media",
    industry: "media",
    archetypeId: "creator_media",
    moduleIds: ["marketing_content", "research_intelligence", "general_operations", "finance_reporting"],
    adaptationId: "adapt_creator",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "nonprofit_ops",
    version: "1.0.0",
    name: "Nonprofit Operations",
    description: "Programs, donor comms, and lean back-office for nonprofits.",
    category: "operational",
    industry: "nonprofit",
    archetypeId: "nonprofit_community",
    moduleIds: ["general_operations", "marketing_content", "finance_reporting", "executive_ops"],
    adaptationId: "adapt_general",
    intakeQuestions: [TEAM_SIZE, NEEDS_AUTOMATION, PRIMARY_OPS],
  },
  // Operational — general_ops remains a legacy TemplateManifest alias.
  {
    key: "sales_department",
    version: "1.0.0",
    name: "Sales Department",
    description: "Pipeline-focused team with light ops support.",
    category: "operational",
    industry: "sales",
    archetypeId: "general_business",
    moduleIds: ["sales_pipeline", "client_success", "executive_ops"],
    adaptationId: "adapt_general",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "marketing_department",
    version: "1.0.0",
    name: "Marketing Department",
    description: "Campaigns, content, and performance analysis.",
    category: "operational",
    industry: "marketing",
    archetypeId: "marketing_agency",
    moduleIds: ["marketing_content", "performance_marketing", "executive_ops"],
    adaptationId: "adapt_general",
    intakeQuestions: [TEAM_SIZE],
  },
  {
    key: "customer_support_department",
    version: "1.0.0",
    name: "Customer Support Department",
    description: "Dedicated CX coverage with ops escalation.",
    category: "operational",
    industry: "support",
    archetypeId: "general_business",
    moduleIds: ["customer_support", "general_operations", "executive_ops"],
    adaptationId: "adapt_general",
    intakeQuestions: [TEAM_SIZE, NEEDS_SUPPORT],
  },
  {
    key: "finance_reporting_team",
    version: "1.0.0",
    name: "Finance and Reporting Team",
    description: "Books, reporting, and owner briefings.",
    category: "operational",
    industry: "finance",
    archetypeId: "general_business",
    moduleIds: ["finance_reporting", "executive_ops", "general_operations"],
    adaptationId: "adapt_professional_services",
    intakeQuestions: [TEAM_SIZE, PRIMARY_OPS],
    intakeDefaults: { primary_ops_focus: "financial_hygiene" },
  },
  {
    key: "executive_office",
    version: "1.0.0",
    name: "Executive Office",
    description: "Owner leverage with light ops and finance.",
    category: "operational",
    industry: "general",
    archetypeId: "general_business",
    moduleIds: ["executive_ops", "general_operations", "finance_reporting"],
    adaptationId: "adapt_general",
    intakeQuestions: [TEAM_SIZE],
  },
];

export function getCuratedPack(key: string): CuratedPack | undefined {
  return CURATED_PACKS.find((p) => p.key === key || p.aliases?.includes(key));
}

export function listCuratedPacks(): CuratedPack[] {
  return CURATED_PACKS;
}
