-- Durable, server-only sliding-window rate-limit events.
-- The application accesses this table exclusively with the secret client.

create table if not exists public.security_rate_limit_events (
  id bigint generated by default as identity primary key,
  bucket text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_security_rate_limit_events_lookup
  on public.security_rate_limit_events (bucket, key_hash, created_at desc);

create index if not exists idx_security_rate_limit_events_created
  on public.security_rate_limit_events (created_at);

alter table public.security_rate_limit_events enable row level security;

revoke all on table public.security_rate_limit_events from anon, authenticated;
revoke all on sequence public.security_rate_limit_events_id_seq from anon, authenticated;
